# Options
set-option global tabstop 2
set-option global indentwidth  2
set-option global scrolloff 0,0
set-option global incsearch true

# Theme
colorscheme gruvbox-dark

# Map jk to Esc
hook global InsertChar k %{ try %{
  exec -draft hH <a-k>jk<ret> d
  exec <esc>
}}

# Relative line number
add-highlighter global/ number-lines -relative
