# BAR CONFIGURATION
window/bar:
  # GENERAL
  providers: ['self']
  width: '{{ self.args.MONITOR_WIDTH }}'
  height: '36'
  position_x: '{{ self.args.MONITOR_X }}'
  position_y: '{{ self.args.MONITOR_Y }}'
  z_order: 'normal'
  shown_in_taskbar: true
  resizable: false
  global_styles: |
    @import "https://www.nerdfonts.com/assets/css/webfont.css";
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
    height: 100%;
    color: #cdd6f4;
    font-family: JetBrainsMono Nerd Font, Segoe UI, Consolas, ui-monospace, monospace;
    font-weight: Semibold;
    font-size: 10px;
    padding: 0px 0px;
    background: #11111b;
  # LEFT SIDE
  group/left:
    styles: |
      display: flex;
      align-items: center;
    # WINDOWS LOGO
    template/logo:
      styles: |
        color: #f5e0dc;
        margin-right: 8px;
        margin-left: 8px;
      template: |
        <i class="nf nf-fa-windows"></i>
    # WORKSPACE TAG
    template/glazewm_workspaces:
      styles: |
        background: #11111b;
        color: #cdd6f4;
        display: flex;
        align-items: center;
        .workspace {
          background: #11111b;
          padding: 8px 8px;
          color: #ffffff;
          border: none;
          border-radius: 0px;
          cursor: pointer;
          &.displayed {
            background: #11111b;
          }
          &.focused {
            color: #a6e3a1;
            weight: bold;
          }
          &:hover {
            color: #89b4fa;
          }
        }
      providers: ['glazewm']
      events:
        - type: 'click'
          fn_path: 'script.js#focusWorkspace'
          selector: '.workspace'
      template: |
        @for (workspace of glazewm.currentWorkspaces) {
          <button
            class="workspace {{ workspace.hasFocus ? 'focused' : '' }} {{ workspace.isDisplayed ? 'displayed' : '' }}"
            id="{{ workspace.name }}"
          >
            {{ workspace.displayName ?? workspace.name }}
          </button>
        }
  # CENTER
  group/center:
    styles: |
      justify-self: center;
    # WINDOW TITLE NAME
    template/glazewm_current_window:
      providers: ['glazewm', 'date']
      styles: |
        .current-window {
          color: #cdd6f4;
          white-space: nowrap;
          max-width: 300px;
          overflow: hidden;
          text-overflow: ellipsis;
        }
        .time {
          color: #f5c2e7;
        }
      template: |
        @if (glazewm.focusedContainer?.type === 'window') {
          <span class="current-window">
            {{ glazewm.focusedContainer.title.length > 80 ? glazewm.focusedContainer.title.slice(0, 80) + '...' : glazewm.focusedContainer.title }}
          </span>
        } @else {
          <span class="time">
            {{ date.toFormat(date.now, 'EEE    d MMM t') }}
          </span>
        }
  # RIGHT SIDE
  group/right:
    styles: |
      justify-self: end;
      display: flex;
    # CPU
    template/cpu:
      providers: ['cpu']
      styles: |
        color: #f38ba8;
        margin-right: 8px;
        margin-left: 8px;
      template: |
        <i class="nf nf-oct-cpu"></i>
        <span>{{ Math.round(cpu.usage) }}%</span>
    # RAM
    template/memory:
      providers: ['memory']
      styles: |
        color: #fab387;
        margin-right: 8px;
        margin-left: 8px;
      template: |
        <i class="nf nf-oct-stack"></i>
        {{ Math.round(memory.usage) }}%
    # BATTERY
    template/battery:
      providers: ['battery']
      styles: |
        color: #a6e3a1;
        margin-right: 8px;
        margin-left: 8px;
      template: |
        @if (battery.chargePercent > 90) {<i class="nf nf-md-battery"></i>}
        @else if (battery.chargePercent > 50) {<i class="nf nf-md-battery_50"></i>}
        @else if (battery.chargePercent > 25) {<i class="nf nf-md-battery_30"></i>}
        @else {<i class="nf nf-md-battery_10"></i>}
        {{ Math.round(battery.chargePercent) }}%
    # DATETIME
    template/clock:
      providers: ['date']
      styles: |
        color: #cba6f7;
        margin-right: 8px;
        margin-left: 8px;
      template: |
        <i class="nf nf-fa-calendar"></i>
        {{ date.toFormat(date.now, 'yyyy-MM-dd HH:mm') }}
