# BAR CONFIGURATION
window/bar:
  # GENERAL
  providers: ['self']
  width: '{{ self.args.MONITOR_WIDTH }}'
  height: '40'
  position_x: '{{ self.args.MONITOR_X }}'
  position_y: '{{ self.args.MONITOR_Y }}'
  z_order: 'normal'
  shown_in_taskbar: true
  resizable: false
  global_styles: |
    @import "https://www.nerdfonts.com/assets/css/webfont.css";
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
    height: 100%;
    color: #ffffff;
    font-family: Segoe UI, Consolas, ui-monospace, monospace;
    font-weight: Semibold;
    font-size: 12px;
    padding: 0px 0px;
    background: #000000;
  # LEFT SIDE
  group/left:
    styles: |
      display: flex;
      align-items: center;
    # WINDOWS LOGO
    template/logo:
      styles: |
        color: #ffffff;
        margin-right: 8px;
        margin-left: 8px;
      template: |
        <i class="nf nf-fa-windows"></i>
    # WORKSPACE TAG
    template/glazewm_workspaces:
      styles: |
        display: flex;
        align-items: center;
        .workspace {
          background: #000000;
          padding: 8px 8px;
          color: #ffffff;
          border: none;
          border-radius: 0px;
          cursor: pointer;
          &.displayed {
            background: #000000;
          }
          &.focused {
            background: #0078d7;
          }
          &:hover {
            background: #ffffff;
            color: #000000;
          }
        }
      providers: ['glazewm']
      events:
        - type: 'click'
          fn_path: 'script.js#focusWorkspace'
          selector: '.workspace'
      template: |
        @for (workspace of glazewm.currentWorkspaces) {
          <button
            class="workspace {{ workspace.hasFocus ? 'focused' : '' }} {{ workspace.isDisplayed ? 'displayed' : '' }}"
            id="{{ workspace.name }}"
          >
            {{ workspace.displayName ?? workspace.name }}
          </button>
        }
  # CENTER
  group/center:
    styles: |
      justify-self: center;
  # RIGHT SIDE
  group/right:
    styles: |
      justify-self: end;
      display: flex;
    # CPU
    template/cpu:
      providers: ['cpu']
      styles: |
        margin-right: 8px;
        margin-left: 8px;
      template: |
        <i class="nf nf-oct-cpu"></i>
        <span>{{ Math.round(cpu.usage) }}%</span>
    # RAM
    template/memory:
      providers: ['memory']
      styles: |
        margin-right: 8px;
        margin-left: 8px;
      template: |
        <i class="nf nf-oct-stack"></i>
        {{ Math.round(memory.usage) }}%
    # BATTERY
    template/battery:
      providers: ['battery']
      styles: |
        margin-right: 8px;
        margin-left: 8px;
      template: |
        @if (battery.chargePercent > 90) {<i class="nf nf-md-battery"></i>}
        @else if (battery.chargePercent > 50) {<i class="nf nf-md-battery_50"></i>}
        @else if (battery.chargePercent > 25) {<i class="nf nf-md-battery_30"></i>}
        @else {<i class="nf nf-md-battery_10"></i>}
        {{ Math.round(battery.chargePercent) }}%
    # DATETIME
    template/clock:
      providers: ['date']
      styles: |
        margin-right: 8px;
        margin-left: 8px;
      template: |
        <i class="nf nf-fa-calendar"></i>
        {{ date.toFormat(date.now, 'yyyy-MM-dd HH:mm') }}
