# MAPPING #
bind r source-file ~/.tmux.conf \; display "~/.tmux.conf is reloaded..."
bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# OPTIONS #
setw -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g default-terminal "screen-256color"
setw -g monitor-activity on
set -g visual-activity on

# CLIPBOARD #
# copy to X11 clipboard
if -b 'command -v xsel > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | xsel -i -b"'
if -b '! command -v xsel > /dev/null 2>&1 && command -v xclip > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | xclip -i -selection clipboard >/dev/null 2>&1"'
# copy to macOS clipboard
if -b 'command -v pbcopy > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | pbcopy"'
if -b 'command -v reattach-to-user-namespace > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | reattach-to-user-namespace pbcopy"'
# copy to Windows clipboard
if -b 'command -v clip.exe > /dev/null 2>&1' 'bind y run -b "tmux save-buffer - | clip.exe"'
if -b '[ -c /dev/clipboard ]' 'bind y run -b "tmux save-buffer - > /dev/clipboard"'

# THEME #

# Status
set -g status-position bottom
set -g status "on"
set -g status-bg "#000000"
set -g status-fg "#ffffff"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# Messages
set -g message-style fg="#00ff00",bg="#000000",align="centre"
set -g message-command-style fg="#00ff00",bg="#000000",align="centre"

# Panes
set -g pane-border-style fg="#ffffff"
set -g pane-active-border-style fg="#00ff00"

# Windows
setw -g window-status-activity-style fg="#ffffff",bg="#000000",none
setw -g window-status-separator ""
setw -g window-status-style fg="#ffffff",bg="#000000",none

# Status Line
set -g status-left "#[fg=colour232,bg=colour202,bold]#{?client_prefix, <Prefix> ,}#[fg=colour255,bg=colour234,bold][#S] "
set -g status-right "#[fg=#000000,bg=#00ffff] #W "

# Current Directory
setw -g window-status-format "#[fg=#000000,bg=#ff00ff] #I:#[fg=#ffffff,bg=#808080]#{b:pane_current_path} "
setw -g window-status-current-format "#[fg=#000000,bg=#ffff00] <#I>:#[fg=#000000,bg=#ffff00]#{b:pane_current_path} "

# Modes
setw -g clock-mode-colour "#0ff0f0"
setw -g mode-style "fg=#000000 bg=#ffffff bold"
