#!/usr/bin/bash

preload = /home/cya/Documents/wallpaper/wallpaper1.jpg
wallpaper = eDP-1,/home/cya/Documents/wallpaper/wallpaper1.jpg
wallpaper = HDMI-A-1,/home/cya/Documents/wallpaper/wallpaper1.jpg
