#!/usr/bin/bash

general {
  no_fade_in = false
  no_fade_out = false
  hide_cursor = false
  grace = 0
  disable_loading_bar = false
}
input-field {
  monitor =
  fade_on_empty = false
}
background {
  color = 0xff000000
}
