#!/bin/bash

options=(
  style=round
  width=6.0
  hidpi=off
  active_color="gradient(top_left=0xdd007aff,bottom_right=0xfff5a97f)"
  inactive_color="gradient(top_left=0xff414550,bottom_right=0xff000000)"
  background_color=0x30000000
)

borders "${options[@]}"
