#!/usr/bin/env sh

options=(
	style=round
	width=6.0
	hidpi=off
	active_color="gradient(top_left=0xffa6da95,bottom_right=0xffeed49f)"
	inactive_color="gradient(top_left=0xffed8796,bottom_right=0xfff5a97f)"
	background_color=0xff000000
)
borders "${options[@]}"
