#!/bin/zsh

options=(
  style=round
  width=4.0
  hidpi=off
  active_color="gradient(top_left=0xff61afef,bottom_right=0xffde98fd)"
  inactive_color="gradient(top_left=0xff42464e,bottom_right=0xff6f737b)"
  background_color=0xff1b1f27
)

borders "${options[@]}"
