after-login-command = []
after-startup-command = []
exec-on-workspace-change = []
start-at-login = true
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
default-root-container-layout = "tiles"

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 12
outer.bottom = 12
outer.right = 12
outer.top = 12

[mode.main.binding]
alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'
alt-j = 'focus left'
alt-k = 'focus right'
alt-h = 'resize smart -50'
alt-l = 'resize smart +50'
alt-tab = 'layout floating tiling'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-0 = 'workspace 10'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-0 = 'move-node-to-workspace 10'
