#!/bin/zsh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

declare -A config
config=(
  [external_bar]=all:0:32
  [menubar_opacity]=1.0
  [mouse_follows_focus]=off
  [focus_follows_mouse]=off
  [display_arrangement_order]=default
  [window_origin_display]=default
  [window_placement]=second_child
  [window_zoom_persist]=on
  [window_shadow]=off
  [window_animation_duration]=0.0
  [window_animation_easing]=ease_out_circ
  [window_opacity_duration]=0.0
  [active_window_opacity]=1.0
  [normal_window_opacity]=0.8
  [window_opacity]=on
  [window_border]=on
  [active_window_border_color]=0xFF88C0D0
  [normal_window_border_color]=0x002E3440
  [insert_feedback_color]=0xFFA3BE8C
  [split_ratio]=0.50
  [split_type]=auto
  [auto_balance]=off
  [top_padding]=8
  [bottom_padding]=8
  [right_padding]=8
  [left_padding]=8
  [window_gap]=8
  [layout]=bsp
  [mouse_modifier]=fn
  [mouse_action1]=move
  [mouse_action2]=resize
  [mouse_drop_action]=swap
)

for key val in ${(kv)config}; do
    yabai -m config $key $val
done

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m rule --add app='^Finder$' manage=off
yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded..."
