#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config external_bar off:0:0
yabai -m config menubar_opacity 1.0
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse on
yabai -m config display_arrangement_order default
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_zoom_persist on
yabai -m config window_shadow on
yabai -m config window_animation_duration 0.0
yabai -m config window_animation_easing ease_out_circ
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.8
yabai -m config window_opacity on
yabai -m config window_border on
yabai -m config active_window_border_color 0xFF88C0D0
yabai -m config normal_window_border_color 0x002E3440
yabai -m config insert_feedback_color 0xFFA3BE8C
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance off
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8
yabai -m config layout bsp
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m rule --add app='^Finder$' manage=off
yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded..."
