return {
  {
    "catppuccin/nvim",
    lazy = false,
    name = "catppuccin",
    priority = 1000,
    config = function()
      require("catppuccin").setup({
        flavour = "mocha",
        background = {
          light = "latte",
          dark = "mocha",
        },
        compile_path = vim.fn.stdpath "cache" .. "/catppuccin",
        transparent_background = false,
        show_end_of_buffer = false,
        term_colors = false,
        dim_inactive = {
          enabled = true,
          shade = "dark",
          percentage = 0.30,
        },
        no_italic = true,
        no_bold = false,
        no_underline = false,
        styles = {
          comments = { "bold" },
          conditionals = { "bold" },
          loops = {},
          functions = {},
          keywords = {},
          strings = {},
          variables = {},
          numbers = {},
          booleans = {},
          properties = {},
          types = {},
          operators = {},
        },
        color_overrides = {
          mocha = {
            -- base = "#000000",
          },
        },
        custom_highlights = {},
        highlight_overrides = {
          mocha = function(color)
            return {
              Comment = { fg = color.subtext2 },
              CursorLineNr = { fg = color.green, style = { "bold" } },
              ["@variable.member"] = { fg = color.text },
              ["@keyword.return"] = { fg = color.pink },
            }
          end,
        },
        default_integrations = true,
        integrations = {
          aerial = false,
          alpha = false,
          barbar = false,
          barbecue = {
            dim_dirname = false,
            bold_basename = false,
            dim_context = false,
            alt_background = false,
          },
          beacon = false,
          coc_nvim = false,
          colorful_winsep = {
            enabled = false,
            color = "red",
          },
          dashboard = false,
          diffview = true,
          dropbar = {
            enabled = false,
            color_mode = false,
          },
          fern = false,
          fidget = false,
          flash = false,
          gitsigns = true,
          harpoon = false,
          headlines = false,
          hop = false,
          indent_blankline = {
            enabled = true,
            scope_color = "rosewater",
            colored_indent_levels = true,
          },
          leap = false,
          lightspeed = false,
          lsp_saga = false,
          markdown = true,
          mason = true,
          mini = {
            enabled = false,
            indentscope_color = "",
          },
          neotree = false,
          neogit = false,
          neotest = false,
          noice = false,
          NormalNvim = false,
          notifier = false,
          cmp = true,
          dap = true,
          dap_ui = true,
          native_lsp = {
            enabled = true,
            virtual_text = {
              errors = { "bold" },
              hints = { "bold" },
              warnings = { "bold" },
              information = { "bold" },
              ok = { "bold" },
            },
            underlines = {
              errors = { "underline" },
              hints = { "underline" },
              warnings = { "underline" },
              information = { "underline" },
              ok = { "underline" },
            },
            inlay_hints = {
              background = true,
            },
          },
          navic = {
            enabled = false,
            custom_bg = "NONE",
          },
          notify = true,
          semantic_tokens = true,
          nvimtree = true,
          treesitter_context = true,
          treesitter = true,
          ts_rainbow = false,
          ts_rainbow2 = false,
          ufo = false,
          window_picker = false,
          octo = false,
          overseer = false,
          pounce = false,
          rainbow_delimiters = true,
          symbols_outline = false,
          telekasten = false,
          telescope = {
            enabled = true,
            -- style = "nvchad"
          },
          lsp_trouble = true,
          gitgutter = false,
          illuminate = {
            enabled = false,
            lsp = false
          },
          sandwich = false,
          vim_sneak = false,
          vimwiki = false,
          which_key = true,
        },
      })
      vim.cmd.colorscheme "catppuccin"
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    version = false,
    build = ":TSUpdate",
    lazy = true,
    event = "VeryLazy",
    opts = {
      highlight = { enable = true },
      indent = { enable = true },
      ensure_installed = {
        "bash",
        "c",
        "lua",
        "python",
        "query",
        "vim",
      },
    },
    config = function(_, opts)
      require("nvim-treesitter.configs").setup(opts)
    end,
  },
  {
    "windwp/nvim-autopairs",
    lazy = true,
    event = "InsertEnter",
    opts = {},
  },
  {
    "numToStr/Comment.nvim",
    lazy = true,
    event = "VeryLazy",
    opts = {},
  },
}

