"use strict";
module.exports = {
    config: {
        updateChannel: 'stable',
        fontSize: 12,
        fontFamily: '"JetBrainsMono Nerd Font", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
        fontWeight: '500',
        fontWeightBold: 'bold',
        lineHeight: 1.25,
        letterSpacing: 0,
        cursorColor: '#e06c75',
        cursorAccentColor: '#1b1f27',
        cursorShape: 'BLOCK',
        cursorBlink: true,
        foregroundColor: '#abb2bf',
        backgroundColor: '#1b1f27',
        selectionColor: '#61afef',
        borderColor: '#61afef',
        css: '',
        termCSS: '',
        workingDirectory: '',
        showHamburgerMenu: '',
        showWindowControls: '',
        padding: '12px 12px 12px 12px',
        colors: {
            black: '#1b1f27',
            red: '#e06c75',
            green: '#98c379',
            yellow: '#e7c787',
            blue: '#61afef',
            magenta: '#c882e7',
            cyan: '#a3b8ef',
            white: '#abb2bf',
            lightBlack: '#1b1f27',
            lightRed: '#DE8C92',
            lightGreen: '#7eca9c',
            lightYellow: '#EBCB8B',
            lightBlue: '#81A1C1',
            lightMagenta: '#de98fd',
            lightCyan: '#519ABA',
            lightWhite: '#abb2bf',
            limeGreen: '#7eca9c',
            lightCoral: '#fca2aa',
        },
        shell: '',
        shellArgs: ['--login'],
        env: {},
        bell: 'SOUND',
        copyOnSelect: true,
        defaultSSHApp: true,
        quickEdit: false,
        macOptionSelectionMode: 'vertical',
        webGLRenderer: true,
        webLinksActivationKey: '',
        disableLigatures: false,
        disableAutoUpdates: true,
        screenReaderMode: false,
        preserveCWD: true,
    },
    plugins: [],
    localPlugins: [],
    keymaps: {
    },
};
