[general]
import = []
working_directory = "None"
live_config_reload = true
ipc_socket = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 10, y = 10 }
dynamic_padding = false
decorations = "Full"
opacity = 0.95
blur = true
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "OnlyLeft"

[scrolling]
history = 5000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.00
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
line_indicator = { foreground = "None", background = "None" }
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.footer_bar]
foreground = "#181818"
background = "#d8d8d8"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.primary]
background = "#181818"
foreground = "#d8d8d8"
dim_foreground = "#828482"
bright_foreground = "None"

[colors.search.matches]
foreground = "#181818"
background = "#ac4242"

[colors.search.focused_match]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.start]
foreground = "#181818"
background = "#f4bf75"

[colors.hints.end]
foreground = "#181818"
background = "#ac4242"

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"

[colors.dim]
black = "#0f0f0f"
red = "#712b2b"
green = "#5f6f3a"
yellow = "#a17e4d"
blue = "#456877"
magenta = "#704d68"
cyan = "#4d7770"
white = "#8e8e8e"

[[colors.indexed_colors]]
index = 16
color = "#f8f8f8"

[[colors.indexed_colors]]
index = 17
color = "#d8d8d8"

[bell]
animation = "Linear"
duration = 2
color = "#ac4242"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Block"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Always"

[terminal]
shell = { program = "/bin/bash", args = ["-l"] }
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
bindings = []

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post_processing = true
persist = true
action = "Select"
command = "xdg-open"
binding = { key = "O", mods = "Control|Shift" }
mouse = { mods = "alt", enabled = true }

[keyboard]
bindings = []

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
