" {{{ Reference }}}
" https://github.com/junegunn/vim-plug/wiki/tips
" https://github.com/skywind3000/vim-init
" https://github.com/wklken/k-vim
" https://github.com/amix/vimrc
" https://gitee.com/mirrorvim/vim-fast/blob/master/vimrc-no-plug
" https://github.com/chenxuan520/vim-fast

" {{{ Options }}}
filetype on
filetype plugin on
filetype indent on
syntax enable
syntax on
set autoread
set backspace=indent,eol,start
set ruler
set number
set relativenumber
set cursorline
set cursorcolumn
set colorcolumn=80
set splitbelow
set splitright
set clipboard^=unnamed,unnamedplus
set nowrap
set background=dark
set showtabline=2
set laststatus=2
set wildmenu
set autoindent
set cindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smarttab
set hlsearch
set incsearch
set ignorecase
set smartcase
set nobackup
set noswapfile
set termguicolors
colorscheme desert

" {{{ Keybinding }}}
let mapleader = ' '
let maplocalleader = '\'
nnoremap <leader>CE <cmd>edit $MYVIMRC<cr>
nnoremap <leader>CR <cmd>source $MYVIMRC<cr>
inoremap jk <esc>

" {{{ rtp plugins }}}
let g:loaded_getscriptPlugin=1
let g:loaded_gzip=1
let g:loaded_logiPat=1
let g:loaded_manpager=1
let g:loaded_matchit=1
let g:loaded_matchparen=1
let g:loaded_netrwPlugin=1
let g:loaded_rrhelper=1
let g:loaded_spellfile=1
let g:loaded_tarPlugin=1
let g:loaded_tohtml=1
let g:loaded_vimballPlugin=1
let g:loaded_zipPlugin=1

" {{{ autocmd }}}
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line('$') | exe "normal! g'\"" | endif
autocmd bufenter * setlocal formatoptions-=r formatoptions-=c formatoptions-=o
autocmd BufWinEnter * if getfsize(expand('%')) > 1048576 | syntax clear | endif

" {{{ Bootstrap vim-plug }}}
let data_dir = has('win32') || has('win64') ? '$HOME\vimfiles' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  if has('win32') || has('win64')
    silent execute '!powershell -Command "New-Item -Path "'.data_dir.' -Name autoload -Type Directory -Force; Invoke-WebRequest -Uri https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim -OutFile '.data_dir.'\autoload\plug.vim"'
  else
    silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  endif
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) > 0 | PlugInstall --sync | source $MYVIMRC | endif

" {{{ vim-plug }}}
call plug#begin()
Plug 'sheerun/vim-polyglot', {'on': []}
Plug 'morhetz/gruvbox', {'on': []}
Plug 'itchyny/lightline.vim', {'on': []}
Plug 'Yggdroot/indentLine', {'on': []}
Plug 'wellle/context.vim', {'on': []}
Plug 'ap/vim-buftabline', {'on': []}
Plug 'andymass/vim-matchup', {'on': []}
Plug 'ntpeters/vim-better-whitespace', {'on': []}
Plug 'LunarWatcher/auto-pairs', {'on': []}
Plug 'luochen1990/rainbow', {'on': []}
Plug 'tpope/vim-commentary', {'on': []}
Plug 'airblade/vim-gitgutter', {'on': []}
Plug 'dense-analysis/ale', {'on': []}
Plug 'junegunn/fzf', {'do': {->fzf#install()}}
Plug 'junegunn/fzf.vim', {'on': ['Files', 'Buffers', 'Colors', 'Lines', 'BLines', 'History', 'Commands']}
Plug 'mbbill/undotree', {'on': ['UndotreeToggle']}
Plug 'easymotion/vim-easymotion', {'on': ['<Plug>(easymotion-overwin-f)', '<Plug>(easymotion-overwin-line)']}
call plug#end()

augroup vim_polyglot
  autocmd!
  autocmd BufReadPost * call plug#load('vim-polyglot')
        \| autocmd! vim_polyglot
augroup END

augroup gruvbox
  autocmd!
  autocmd BufReadPost * call plug#load('gruvbox')
        \| autocmd! gruvbox
        \| colorscheme gruvbox
augroup END

augroup lightline
  autocmd!
  autocmd BufReadPost * call plug#load('lightline.vim')
        \| autocmd! lightline
        \| let g:lightline={'colorscheme': 'apprentice'}
        \| call lightline#enable()
augroup END

augroup indentline
  autocmd!
  autocmd BufReadPost * call plug#load('indentLine')
        \| autocmd! indentline
        \| IndentLinesToggle
augroup END

augroup context_vim
  autocmd!
  autocmd BufReadPost * call plug#load('context.vim')
        \| autocmd! context_vim
        \| ContextEnable
augroup END

augroup vim_buftabline
  autocmd!
  autocmd BufReadPost * call plug#load('vim-buftabline')
        \| autocmd! vim_buftabline
augroup END

augroup vim_matchup
  autocmd!
  autocmd BufReadPost * call plug#load('vim-matchup')
        \| autocmd! vim_matchup
augroup END

augroup vim_better_whitespace
  autocmd!
  autocmd BufReadPost * call plug#load('vim-better-whitespace')
        \| autocmd! vim_better_whitespace
augroup END

augroup auto_pairs
  autocmd!
  autocmd InsertEnter * call plug#load('auto-pairs')
        \| autocmd! auto_pairs
        \| call autopairs#AutoPairsTryInit()
augroup END

augroup rainbow
  autocmd!
  autocmd BufReadPost * call plug#load('rainbow')
        \| autocmd! rainbow
        \| RainbowToggle
augroup END

augroup vim_commentary
  autocmd!
  autocmd BufReadPost * call plug#load('vim-commentary')
        \| autocmd! vim_commentary
augroup END

augroup vim_gitgutter
  autocmd!
  autocmd BufReadPost * call plug#load('vim-gitgutter')
        \| autocmd! vim_gitgutter
        \| GitGutterEnable
augroup END

augroup ale
  autocmd!
  autocmd BufReadPost * call plug#load('ale')
        \| autocmd! ale
augroup END

let g:fzf_layout={'down': '25%'}
nnoremap <leader>ff <cmd>Files<cr>
nnoremap <c-x><c-f> <cmd>Files<cr>
nnoremap <leader>fb <cmd>Buffers<cr>
nnoremap <c-x><c-b> <cmd>Buffers<cr>
nnoremap <leader>fc <cmd>Colors<cr>
nnoremap <leader>fs <cmd>BLines<cr>
nnoremap <leader>fS <cmd>Lines<cr>
nnoremap <c-x><c-s> <cmd>BLines<cr>
nnoremap <leader>fr <cmd>History<cr>
nnoremap <c-x><c-r> <cmd>History<cr>
nnoremap <leader><leader> <cmd>Commands<cr>

nnoremap <leader>tu <cmd>UndotreeToggle<cr>

let g:EasyMotion_do_mapping=0
nnoremap <leader>gf <Plug>(easymotion-overwin-f)
nnoremap <leader>gl <Plug>(easymotion-overwin-line)
nnoremap <leader>gw <Plug>(easymotion-overwin-w)
