" {{{ Reference }}}
" https://github.com/junegunn/vim-plug/wiki/tips
" https://github.com/skywind3000/vim-init
" https://github.com/wklken/k-vim
" https://github.com/amix/vimrc
" https://gitee.com/mirrorvim/vim-fast/blob/master/vimrc-no-plug
" https://github.com/chenxuan520/vim-fast

" {{{ Options }}}
filetype on
filetype plugin on
filetype indent on
syntax enable
syntax on
set autoread
set backspace=indent,eol,start
set ruler
set number
set relativenumber
set cursorline
set cursorcolumn
set colorcolumn=80
set splitbelow
set splitright
set clipboard^=unnamed,unnamedplus
set nowrap
set showtabline=2
set laststatus=2
set wildmenu
set autoindent
set cindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smarttab
set hlsearch
set incsearch
set ignorecase
set smartcase
set nobackup
set noswapfile
set notermguicolors
set background=dark
" colorscheme desert

" {{{ Keybinding }}}
let mapleader = ' '
let maplocalleader = '\'
nnoremap <leader>CE <cmd>edit $MYVIMRC<cr>
nnoremap <leader>CR <cmd>source $MYVIMRC<cr>
inoremap jk <esc>

" {{{ rtp plugins }}}
let g:loaded_getscriptPlugin=1
let g:loaded_gzip=1
let g:loaded_logiPat=1
let g:loaded_manpager=1
let g:loaded_matchit=1
let g:loaded_matchparen=1
let g:loaded_netrwPlugin=1
let g:loaded_rrhelper=1
let g:loaded_spellfile=1
let g:loaded_tarPlugin=1
let g:loaded_tohtml=1
let g:loaded_vimballPlugin=1
let g:loaded_zipPlugin=1

" {{{ autocmd }}}
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line('$') | exe "normal! g'\"" | endif
autocmd bufenter * setlocal formatoptions-=r formatoptions-=c formatoptions-=o
autocmd BufWinEnter * if getfsize(expand('%')) > 1048576 | syntax clear | endif
autocmd FileType python setlocal shiftwidth=4 tabstop=4 softtabstop=4

" {{{ Bootstrap vim-plug }}}
if empty(glob('~/.vim/autoload/plug.vim'))
  silent execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd BufWinEnter * PlugInstall --sync | source $MYVIMRC
endif
autocmd BufWinEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) > 0 | PlugInstall --sync | source $MYVIMRC | endif

" {{{ vim-plug }}}
call plug#begin()
Plug 'sheerun/vim-polyglot', {'on': []}
Plug 'mhinz/vim-startify', {'on': []}
Plug 'morhetz/gruvbox', {'on': []}
Plug 'itchyny/lightline.vim', {'on': []}
Plug 'Yggdroot/indentLine', {'on': []}
Plug 'wellle/context.vim', {'on': []}
Plug 'ap/vim-buftabline', {'on': []}
Plug 'andymass/vim-matchup', {'on': []}
Plug 'ntpeters/vim-better-whitespace', {'on': []}
Plug 'LunarWatcher/auto-pairs', {'on': []}
Plug 'luochen1990/rainbow', {'on': []}
Plug 'tpope/vim-commentary', {'on': []}
Plug 'airblade/vim-gitgutter', {'on': []}
Plug 'dense-analysis/ale', {'on': []}
Plug 'ryanoasis/vim-devicons', {'on': []}
Plug 'machakann/vim-highlightedyank', {'on': []}
Plug 'wincent/terminus', {'on': []}
Plug 'dominikduda/vim_current_word', {'on': []}
Plug 'junegunn/fzf', {'do': {->fzf#install()}}
Plug 'liuchengxu/vim-which-key', {'on': ['WhichKey', 'WhichKey!']}
Plug 'junegunn/fzf.vim', {'on': ['Files', 'Buffers', 'Colors', 'Lines', 'BLines', 'History', 'Commands']}
Plug 'mbbill/undotree', {'on': ['UndotreeToggle']}
Plug 'easymotion/vim-easymotion', {'on': ['<Plug>(easymotion-overwin-f)', '<Plug>(easymotion-overwin-line)']}
Plug 'dyng/ctrlsf.vim', {'on': ['CtrlSF']}
Plug 'skywind3000/asyncrun.vim', {'on': ['AsyncRun']}
Plug 'preservim/nerdtree', {'on': ['NERDTreeToggle']}
Plug 'voldikss/vim-floaterm'
call plug#end()

augroup VimPolyglot
  autocmd!
  autocmd BufReadPost * call plug#load('vim-polyglot')
        \| autocmd! VimPolyglot
augroup END

augroup VimStartify
  autocmd!
  autocmd BufEnter * call plug#load('vim-startify')
        \| autocmd! VimStartify
        \| let g:startify_custom_header = [
        \'',
        \'',
        \'   ⣇⣿⠘⣿⣿⣿⡿⡿⣟⣟⢟⢟⢝⠵⡝⣿⡿⢂⣼⣿⣷⣌⠩⡫⡻⣝⠹⢿⣿⣷   ',
        \'   ⡆⣿⣆⠱⣝⡵⣝⢅⠙⣿⢕⢕⢕⢕⢝⣥⢒⠅⣿⣿⣿⡿⣳⣌⠪⡪⣡⢑⢝⣇   ',
        \'   ⡆⣿⣿⣦⠹⣳⣳⣕⢅⠈⢗⢕⢕⢕⢕⢕⢈⢆⠟⠋⠉⠁⠉⠉⠁⠈⠼⢐⢕⢽   ',
        \'   ⡗⢰⣶⣶⣦⣝⢝⢕⢕⠅⡆⢕⢕⢕⢕⢕⣴⠏⣠⡶⠛⡉⡉⡛⢶⣦⡀⠐⣕⢕   ',
        \'   ⡝⡄⢻⢟⣿⣿⣷⣕⣕⣅⣿⣔⣕⣵⣵⣿⣿⢠⣿⢠⣮⡈⣌⠨⠅⠹⣷⡀⢱⢕   ',
        \'   ⡝⡵⠟⠈⢀⣀⣀⡀⠉⢿⣿⣿⣿⣿⣿⣿⣿⣼⣿⢈⡋⠴⢿⡟⣡⡇⣿⡇⡀⢕   ',
        \'   ⡝⠁⣠⣾⠟⡉⡉⡉⠻⣦⣻⣿⣿⣿⣿⣿⣿⣿⣿⣧⠸⣿⣦⣥⣿⡇⡿⣰⢗⢄   ',
        \'   ⠁⢰⣿⡏⣴⣌⠈⣌⠡⠈⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣬⣉⣉⣁⣄⢖⢕⢕⢕   ',
        \'   ⡀⢻⣿⡇⢙⠁⠴⢿⡟⣡⡆⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣵⣵⣿   ',
        \'   ⡻⣄⣻⣿⣌⠘⢿⣷⣥⣿⠇⣿⣿⣿⣿⣿⣿⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿   ',
        \'   ⣷⢄⠻⣿⣟⠿⠦⠍⠉⣡⣾⣿⣿⣿⣿⣿⣿⢸⣿⣦⠙⣿⣿⣿⣿⣿⣿⣿⣿⠟   ',
        \'   ⡕⡑⣑⣈⣻⢗⢟⢞⢝⣻⣿⣿⣿⣿⣿⣿⣿⠸⣿⠿⠃⣿⣿⣿⣿⣿⣿⡿⠁⣠   ',
        \'   ⡝⡵⡈⢟⢕⢕⢕⢕⣵⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣿⣿⣿⣿⣿⠿⠋⣀⣈⠙   ',
        \'   ⡝⡵⡕⡀⠑⠳⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⢉⡠⡲⡫⡪⡪⡣   ',
        \'',
        \'',
        \ ]
augroup END

augroup Gruvbox
  autocmd!
  autocmd BufEnter,BufReadPost * call plug#load('gruvbox')
        \| autocmd! Gruvbox
        \| colorscheme gruvbox
augroup END

augroup LightLine
  autocmd!
  autocmd BufReadPost * call plug#load('lightline.vim')
        \| autocmd! LightLine
        \| let g:lightline={'colorscheme': 'apprentice'}
        \| call lightline#enable()
augroup END

augroup IndentLine
  autocmd!
  autocmd BufReadPost * call plug#load('indentLine')
        \| autocmd! IndentLine
        \| IndentLinesToggle
augroup END

augroup ContextVim
  autocmd!
  autocmd BufReadPost * call plug#load('context.vim')
        \| autocmd! ContextVim
        \| ContextEnable
augroup END

augroup VimBufTabLine
  autocmd!
  autocmd BufReadPost * call plug#load('vim-buftabline')
        \| autocmd! VimBufTabLine
augroup END

augroup VimMatchUp
  autocmd!
  autocmd BufReadPost * call plug#load('vim-matchup')
        \| autocmd! VimMatchUp
augroup END

augroup VimBetterWhitespace
  autocmd!
  autocmd BufReadPost * call plug#load('vim-better-whitespace')
        \| autocmd! VimBetterWhitespace
augroup END

augroup AutoPairs
  autocmd!
  autocmd InsertEnter * call plug#load('auto-pairs')
        \| autocmd! AutoPairs
        \| call autopairs#AutoPairsTryInit()
augroup END

augroup Rainbow
  autocmd!
  autocmd BufReadPost * call plug#load('rainbow')
        \| autocmd! Rainbow
        \| RainbowToggle
augroup END

augroup VimCommentary
  autocmd!
  autocmd BufReadPost * call plug#load('vim-commentary')
        \| autocmd! VimCommentary
augroup END

augroup VimGitGutter
  autocmd!
  autocmd BufReadPost * call plug#load('vim-gitgutter')
        \| autocmd! VimGitGutter
        \| GitGutterEnable
augroup END

augroup ALE
  autocmd!
  autocmd BufReadPost * call plug#load('ale')
        \| autocmd! ALE
augroup END

augroup VimDevIcons
  autocmd!
  autocmd BufReadPost * call plug#load('vim-devicons')
        \| autocmd! VimDevIcons
augroup END

augroup VimHighlightedYank
  autocmd!
  autocmd BufReadPost * call plug#load('vim-highlightedyank')
        \| autocmd! VimHighlightedYank
        \| let g:highlightedyank_highlight_duration=2500
augroup END

augroup Terminus
  autocmd!
  autocmd InsertEnter * call plug#load('terminus')
        \| autocmd! Terminus
augroup END

augroup VimCurrentWord
  autocmd!
  autocmd BufReadPost * call plug#load('vim_current_word')
        \| autocmd! VimCurrentWord
augroup END

nnoremap <silent><leader> :<c-u>WhichKey '<space>'<cr>
nnoremap <silent><localleader> :<c-u>WhichKey  '\'<cr>

let g:fzf_layout={'down': '25%'}
nnoremap <leader>ff <cmd>Files<cr>
nnoremap <c-x><c-f> <cmd>Files<cr>
nnoremap <leader>fb <cmd>Buffers<cr>
nnoremap <c-x><c-b> <cmd>Buffers<cr>
nnoremap <leader>fc <cmd>Colors<cr>
nnoremap <leader>fs <cmd>BLines<cr>
nnoremap <leader>fS <cmd>Lines<cr>
nnoremap <c-s> <cmd>BLines<cr>
nnoremap <leader>fr <cmd>History<cr>
nnoremap <c-x><c-r> <cmd>History<cr>
nnoremap <leader><leader> <cmd>Commands<cr>

nnoremap <leader>tu <cmd>UndotreeToggle<cr>

let g:EasyMotion_do_mapping=0
nnoremap <leader>gf <Plug>(easymotion-overwin-f)
nnoremap <leader>gl <Plug>(easymotion-overwin-line)
nnoremap <leader>gw <Plug>(easymotion-overwin-w)

let g:NERDTreeShowHidden=1
nnoremap <leader>tn <cmd>NERDTreeToggle<cr>

let g:floaterm_wintype='split'
let g:floaterm_height=0.3
nnoremap <leader>tt <cmd>FloatermNew<cr>
tnoremap <leader>tt <c-\><c-n><cmd>FloatermKill<cr>
