return {
	{
		"catppuccin/nvim",
		name = "catppuccin",
		lazy = false,
		config = function()
			require("catppuccin").setup({
				flavour = "auto",
				background = {
					light = "latte",
					dark = "mocha",
				},
				transparent_background = false,
				show_end_of_buffer = false,
				term_colors = false,
				dim_inactive = {
					enabled = false,
					shade = "dark",
					percentage = 0.15,
				},
				no_italic = false,
				no_bold = false,
				no_underline = false,
				styles = {
					comments = { "italic", "bold" },
					conditionals = { "italic" },
					loops = {},
					functions = {},
					keywords = { "italic" },
					strings = {},
					variables = {},
					numbers = {},
					booleans = {},
					properties = {},
					types = {},
					operators = {},
				},
				color_overrides = {
					mocha = {
						base = "#000000",
						mantle = "#000000",
						crust = "#000000",
					},
				},
				custom_highlights = function(color)
					return {
						Comments = { fg = color.subtext0 },
					}
				end,
				default_integrations = true,
				integrations = {
					aerial = false,
					alpha = true,
					barbar = false,
					barbecue = {
						dim_dirname = true, -- directory name is dimmed by default
						bold_basename = true,
						dim_context = false,
						alt_background = false,
					},
					beacon = false,
					coc_nvim = false,
					colorful_winsep = {
						enabled = false,
						color = "red",
					},
					dashboard = true,
					diffview = false,
					dropbar = {
						enabled = false,
						color_mode = false, -- enable color for kind's texts, not just kind's icons
					},
					fern = false,
					fidget = true,
					flash = true,
					fzf = true,
					gitsigns = true,
					grug_far = false,
					harpoon = false,
					headlines = false,
					hop = false,
					indent_blankline = {
						enabled = true,
						scope_color = "pink",
						colored_indent_levels = false,
					},
					leap = false,
					lightspeed = false,
					lir = {
						enabled = false,
						git_status = false,
					},
					lsp_saga = false,
					markdown = true,
					mason = false,
					mini = {
						enabled = true,
						indentscope_color = "",
					},
					neotree = false,
					neogit = true,
					neotest = false,
					noice = true,
					NormalNvim = false,
					notifier = false,
					cmp = true,
					dap = true,
					dap_ui = true,
					native_lsp = {
						enabled = true,
						virtual_text = {
							errors = { "italic" },
							hints = { "italic" },
							warnings = { "italic" },
							information = { "italic" },
							ok = { "italic" },
						},
						underlines = {
							errors = { "underline" },
							hints = { "underline" },
							warnings = { "underline" },
							information = { "underline" },
							ok = { "underline" },
						},
						inlay_hints = {
							background = true,
						},
					},
					navic = {
						enabled = false,
						custom_bg = "NONE",
					},
					notify = true,
					semantic_tokens = true,
					nvim_surround = false,
					nvimtree = true,
					treesitter_context = true,
					treesitter = true,
					ts_rainbow2 = false,
					ts_rainbow = false,
					ufo = true,
					window_picker = false,
					octo = false,
					overseer = false,
					pounce = false,
					rainbow_delimiters = true,
					render_markdown = true,
					symbols_outline = true,
					telekasten = false,
					telescope = {
						enabled = true,
						style = "nvchad",
					},
					lsp_trouble = false,
					dadbod_ui = false,
					gitgutter = false,
					illuminate = {
						enabled = true,
						lsp = false,
					},
					sandwich = false,
					vim_sneak = false,
					vimwiki = false,
					which_key = true,
				},
			})
			vim.cmd.colorscheme("catppuccin")
		end,
	},
}
