"use strict";
module.exports = {
    config: {
        updateChannel: 'stable',
        fontSize: 12,
        fontFamily: '"JetBrainsMono Nerd Font", Monaco, Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
        fontWeight: 'normal',
        fontWeightBold: 'bold',
        lineHeight: 1.2,
        letterSpacing: 1.04,
        cursorColor: '#f7ca88',
        cursorAccentColor: '#181818',
        cursorShape: 'BLOCK',
        cursorBlink: true,
        foregroundColor: '#e8e8e8',
        backgroundColor: '#181818',
        selectionColor: '#f7ca88',
        borderColor: '#86c1b9',
        css: '',
        termCSS: '',
        workingDirectory: '',
        showHamburgerMenu: '',
        padding: '8px 8px 8px 8px',
        colors: {
            black: '#181818',
            red: '#ab4642',
            green: '#a1b56c',
            yellow: '#f7ca88',
            blue: '#7cafc2',
            magenta: '#ba8baf',
            cyan: '#86c1b9',
            white: '#d8d8d8',
            lightBlack: '#585858',
            lightRed: '#ab4642',
            lightGreen: '#a1b56c',
            lightYellow: '#f7ca88',
            lightBlue: '#7cafc2',
            lightMagenta: '#ba8baf',
            lightCyan: '#86c1b9',
            lightWhite: '#e8e8e8',
            limeGreen: '#a1b56c',
            lightCoral: '#ab4642',
        },
        shell: '',
        shellArgs: ['--login'],
        env: {},
        bell: 'SOUND',
        copyOnSelect: true,
        defaultSSHApp: true,
        quickEdit: false,
        macOptionSelectionMode: 'vertical',
        webGLRenderer: true,
        webLinksActivationKey: '',
        disableLigatures: true,
        disableAutoUpdates: false,
        screenReaderMode: false,
        preserveCWD: true,
    },
    plugins: [],
    localPlugins: [],
    keymaps: {},
};
