#!/usr/bin/env sh

# LAUNCH APPLICATIONS
alt - return : /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
alt + shift - return : /opt/homebrew/bin/emacs

# MOVE FOCUS
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# SWAP WINDOW
alt + shift - h : yabai -m window --swap west
alt + shift - j : yabai -m window --swap south
alt + shift - k : yabai -m window --swap north
alt + shift - l : yabai -m window --swap east

# RESIZE WINDOW
ctrl + alt - h : yabai -m window --resize right:-100:0 || yabai -m window --resize left:-100:0
ctrl + alt - j : yabai -m window --resize bottom:0:100 || yabai -m window --resize top:0:100
ctrl + alt - k : yabai -m window --resize bottom:0:-100 || yabai -m window --resize top:0:-100
ctrl + alt - l : yabai -m window --resize right:100:0 || yabai -m window --resize left:100:0

# MOVE TO SPACE
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8
alt - 9 : yabai -m space --focus 9
alt - 0 : yabai -m space --focus 10

# MOVE WINDOW TO OTHER SPACE
alt + shift - 1 : yabai -m window --space 1 && yabai -m space --focus 1
alt + shift - 2 : yabai -m window --space 2 && yabai -m space --focus 2
alt + shift - 3 : yabai -m window --space 3 && yabai -m space --focus 3
alt + shift - 4 : yabai -m window --space 4 && yabai -m space --focus 4
alt + shift - 5 : yabai -m window --space 5 && yabai -m space --focus 5
alt + shift - 6 : yabai -m window --space 6 && yabai -m space --focus 6
alt + shift - 7 : yabai -m window --space 7 && yabai -m space --focus 7
alt + shift - 8 : yabai -m window --space 8 && yabai -m space --focus 8
alt + shift - 9 : yabai -m window --space 9 && yabai -m space --focus 9
alt + shift - 0 : yabai -m window --space 10 && yabai -m space --focus 10

# OTHER MANIPULATIONS
alt + shift - f : yabai -m window --toggle zoom-fullscreen
alt + shift - q : /opt/homebrew/bin/skhd --key "cmd - q"
alt + shift - r : yabai --restart-service && skhd --restart-service
alt + shift - e : yabai --stop-service && skhd --stop-service
