#!/usr/bin/env sh

# Open Terminal
cmd - return : /System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal --single-instance -d ~ &> /dev/null

# Focus Space
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4

# Move Window to Specific Space and Focus Space
shift + cmd - 1 : yabai -m window --space  1 && yabai -m space --focus 1
shift + cmd - 2 : yabai -m window --space  2 && yabai -m space --focus 2
shift + cmd - 3 : yabai -m window --space  3 && yabai -m space --focus 3
shift + cmd - 4 : yabai -m window --space  4 && yabai -m space --focus 4

# Toggle FullScreen
shift + cmd - f : yabai -m window --toggle native-fullscreen

# Toggle Split
shift + cmd - v : yabai -m window --toggle split

# Focus Window
cmd - h : yabai -m window --focus west
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east

# Swap Window
shift + cmd - h : yabai -m window --swap west
shift + cmd - j : yabai -m window --swap south
shift + cmd - k : yabai -m window --swap north
shift + cmd - l : yabai -m window --swap east

# Resize Window
ctrl + cmd - h : yabai -m window --resize right:-100:0 || yabai -m window --resize left:-100:0
ctrl + cmd - j : yabai -m window --resize bottom:0:100 || yabai -m window --resize top:0:100
ctrl + cmd - k : yabai -m window --resize bottom:0:-100 || yabai -m window --resize top:0:-100
ctrl + cmd - l : yabai -m window --resize right:100:0 || yabai -m window --resize left:100:0

# Restart and Quit
shift + cmd - r : yabai --restart-service || skhd --restart-service
shift + cmd - e : yabai --stop-service || skhd --stop-service
