##########
# OPTION #
##########
set-option global tabstop 2
set-option global indentwidth 2
add-highlighter global/ number-lines -relative

#########
# THEME #
#########
colorscheme default

##############
# KEYBINDING #
##############
hook global InsertChar k %{ try %{
  exec -draft hH <a-k>jk<ret> d
  exec -with-hooks <esc>
}}
