"REF: https://github.com/chenxuan520/vim-fast/blob/master/vimrc-no-plug
"REF: https://github.com/skywind3000/vim/tree/master

""" DISTRIBUTED PLUGINS
let g:loaded_gzip=1
let g:loaded_tar=1
let g:loaded_tarPlugin=1
let g:loaded_zip=1
let g:loaded_zipPlugin=1
let g:loaded_getscript=1
let g:loaded_getscriptPlugin=1
let g:loaded_vimball=1
let g:loaded_vimballPlugin=1
let g:loaded_2html_plugin=1
let g:loaded_logiPat=1
let g:loaded_rrhelper=1
let g:loaded_netrw=1
let g:loaded_netrwPlugin=1
let g:loaded_netrwSettings=1
let g:loaded_netrwFileHandlers=1
let g:loaded_matchit=1
let g:loaded_matchparen=1
let g:did_install_default_menus=1

""" OPTIONS
set nocompatible
set clipboard^=unnamed,unnamedplus
set ruler
set number
set relativenumber
set cursorline
set cursorcolumn
set colorcolumn=80
set laststatus=2
set showtabline=2
set timeout
set timeoutlen=500
set ttimeout
set ttimeoutlen=0
set autoindent
set tabstop=2
set shiftwidth=2
set expandtab
set backspace=eol,start,indent
set hlsearch
set incsearch
set ignorecase
set smartcase
set autoread
set autowrite
set nobackup
set noswapfile
set noundofile
set nowrap
set wildmenu
set background=dark
" set termguicolors
set t_Co=256
set t_ut=
syntax on
filetype on
filetype indent plugin on

""" MAPPING
let mapleader="\\"
let maplocalleader=" "
nnoremap <leader>re :edit $MYVIMRC<CR>
nnoremap <leader>rs :source $MYVIMRC<CR>
imap jk <Esc>

""" AUTOCMD
if has("autocmd")
  autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
  autocmd BufReadPost,InsertEnter * setlocal formatoptions-=r formatoptions-=c formatoptions-=o " This auto-command may be reset by some plugins
endif

""" VIM-PLUG

" INSTALL VIM-PLUG AUTOMATICALLY
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" INSTALL UNINSTALLED AUTOMATICALLY
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) > 0 | PlugInstall --sync | source $MYVIMRC | endif

call plug#begin()

" AUTOLOAD
Plug 'tpope/vim-commentary'

" LAZYLOAD
Plug 'mhinz/vim-startify', { 'on': [] }
Plug 'sheerun/vim-polyglot', { 'on': [] }
Plug 'morhetz/gruvbox', { 'on': [] }
Plug 'jnurmine/Zenburn', { 'on': [] }
Plug 'joshdick/onedark.vim', { 'on': [] }
Plug 'junegunn/seoul256.vim', { 'on': [] }
Plug 'tomasiser/vim-code-dark', { 'on': [] }
Plug 'vim-airline/vim-airline', { 'on': [] }
Plug 'vim-airline/vim-airline-themes', { 'on': [] }
Plug 'Yggdroot/indentLine', { 'on': [] }
Plug 'ntpeters/vim-better-whitespace', { 'on': [] }
Plug 'ryanoasis/vim-devicons', { 'on': [] }
Plug 'machakann/vim-highlightedyank', { 'on': [] }
Plug 'dominikduda/vim_current_word', { 'on': [] }
Plug 'LunarWatcher/auto-pairs', { 'on': [] }
Plug 'luochen1990/rainbow', { 'on': [] }
Plug 'dense-analysis/ale', { 'on': [] }
Plug 'airblade/vim-gitgutter', { 'on': [] }
Plug 'wincent/terminus', { 'on': [] }
Plug 'wellle/context.vim', { 'on': [] }
Plug 'liuchengxu/vim-which-key', { 'on': ['WhichKey', 'WhichKey!'] }
Plug 'preservim/nerdtree', { 'on': ['NERDTreeToggle'] }
Plug 'thinca/vim-quickrun', { 'on': ['QuickRun'] }
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim', { 'on': ['Buffers', 'Colors', 'Files', 'Rg', 'Lines', 'BLines', 'History'] }
Plug 'dyng/ctrlsf.vim', { 'on': ['CtrlSF'] }
Plug 'easymotion/vim-easymotion', { 'on': ['<Plug>(easymotion-bd-jk)', '<Plug>(easymotion-bd-w)'] }
Plug 'dstein64/vim-startuptime', { 'on': ['StartupTime'] }

call plug#end()

" VIM-STARTIFY
augroup load_vim_startify
  autocmd!
  autocmd BufEnter * call plug#load('vim-startify')
        \| autocmd! load_theme
        \| let g:startify_custom_header = [
        \'        ⢀⣴⡾⠃⠄⠄⠄⠄⠄⠈⠺⠟⠛⠛⠛⠛⠻⢿⣿⣿⣿⣿⣶⣤⡀  ',
        \'      ⢀⣴⣿⡿⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣸⣿⣿⣿⣿⣿⣿⣿⣷ ',
        \'     ⣴⣿⡿⡟⡼⢹⣷⢲⡶⣖⣾⣶⢄⠄⠄⠄⠄⠄⢀⣼⣿⢿⣿⣿⣿⣿⣿⣿⣿ ',
        \'    ⣾⣿⡟⣾⡸⢠⡿⢳⡿⠍⣼⣿⢏⣿⣷⢄⡀⠄⢠⣾⢻⣿⣸⣿⣿⣿⣿⣿⣿⣿ ',
        \'  ⣡⣿⣿⡟⡼⡁⠁⣰⠂⡾⠉⢨⣿⠃⣿⡿⠍⣾⣟⢤⣿⢇⣿⢇⣿⣿⢿⣿⣿⣿⣿⣿ ',
        \' ⣱⣿⣿⡟⡐⣰⣧⡷⣿⣴⣧⣤⣼⣯⢸⡿⠁⣰⠟⢀⣼⠏⣲⠏⢸⣿⡟⣿⣿⣿⣿⣿⣿ ',
        \' ⣿⣿⡟⠁⠄⠟⣁⠄⢡⣿⣿⣿⣿⣿⣿⣦⣼⢟⢀⡼⠃⡹⠃⡀⢸⡿⢸⣿⣿⣿⣿⣿⡟ ',
        \' ⣿⣿⠃⠄⢀⣾⠋⠓⢰⣿⣿⣿⣿⣿⣿⠿⣿⣿⣾⣅⢔⣕⡇⡇⡼⢁⣿⣿⣿⣿⣿⣿⢣ ',
        \' ⣿⡟⠄⠄⣾⣇⠷⣢⣿⣿⣿⣿⣿⣿⣿⣭⣀⡈⠙⢿⣿⣿⡇⡧⢁⣾⣿⣿⣿⣿⣿⢏⣾ ',
        \' ⣿⡇⠄⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⢻⠇⠄⠄⢿⣿⡇⢡⣾⣿⣿⣿⣿⣿⣏⣼⣿ ',
        \' ⣿⣷⢰⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⢰⣧⣀⡄⢀⠘⡿⣰⣿⣿⣿⣿⣿⣿⠟⣼⣿⣿ ',
        \' ⢹⣿⢸⣿⣿⠟⠻⢿⣿⣿⣿⣿⣿⣿⣿⣶⣭⣉⣤⣿⢈⣼⣿⣿⣿⣿⣿⣿⠏⣾⣹⣿⣿ ',
        \' ⢸⠇⡜⣿⡟⠄⠄⠄⠈⠙⣿⣿⣿⣿⣿⣿⣿⣿⠟⣱⣻⣿⣿⣿⣿⣿⠟⠁⢳⠃⣿⣿⣿ ',
        \'  ⣰⡗⠹⣿⣄⠄⠄⠄⢀⣿⣿⣿⣿⣿⣿⠟⣅⣥⣿⣿⣿⣿⠿⠋  ⣾⡌⢠⣿⡿⠃ ',
        \' ⠜⠋⢠⣷⢻⣿⣿⣶⣾⣿⣿⣿⣿⠿⣛⣥⣾⣿⠿⠟⠛⠉            ',
        \ ]
augroup END

" GRUVBOX ZENBURN ONEDARK.VIM SEOUL256.VIM VIM-CODE-DARK
augroup load_theme
  autocmd!
  autocmd BufReadPost * call plug#load('gruvbox', 'Zenburn', 'onedark.vim', 'seoul256.vim', 'vim-code-dark')
        \| autocmd! load_theme
        \| colorscheme gruvbox
augroup END

" VIM-DEVICONS
augroup load_vim_devicons
  autocmd!
  autocmd BufReadPost * call plug#load('vim-devicons')
        \| autocmd! load_vim_devicons
augroup END

" VIM-AIRLINE VIM_AIRLINE_THEMES
augroup load_vim_airline
  autocmd!
  autocmd BufReadPost * call plug#load('vim-airline', 'vim-airline-themes')
        \| autocmd! load_vim_airline
        \| let g:airline_theme = 'gruvbox'
        \| let g:airline#extensions#tabline#enabled=1
augroup END

" INDENTLINE
augroup load_indentline
  autocmd!
  autocmd BufReadPost * call plug#load('indentLine')
        \| autocmd! load_indentline
        \| let g:indentLine_char_list = ['│']
        \| IndentLinesToggle
augroup END

" VIM-BETTER-WHITESPACE
augroup load_vim_better_whitespace
  autocmd!
  autocmd BufReadPost * call plug#load('vim-better-whitespace')
        \| autocmd! load_vim_better_whitespace
        \| EnableWhitespace
augroup END

" VIM-HIGHLIGHTEDYANK
augroup load_vim_highlightedyank
  autocmd!
  autocmd BufReadPost * call plug#load('vim-highlightedyank')
        \| autocmd! load_vim_highlightedyank
augroup END

" VIM_CURRENT_WORD
augroup load_vim_current_word
  autocmd!
  autocmd BufReadPost * call plug#load('vim_current_word')
        \| autocmd! load_vim_current_word
augroup END

" AUTO-PAIRS
augroup load_auto_pairs
  autocmd!
  autocmd InsertEnter * call plug#load('auto-pairs')
        \| autocmd! load_auto_pairs
        \| call autopairs#AutoPairsTryInit()
augroup END

" ALE
augroup load_ale
  autocmd!
  autocmd BufReadPost * call plug#load('ale')
        \| autocmd! load_ale
augroup END

" VIM-POLYGLOT
augroup load_vim_polyglot
  autocmd!
  autocmd InsertEnter * call plug#load('vim-polyglot')
        \| autocmd! load_vim_polyglot
augroup END

" RAINBOW
augroup load_rainbow
  autocmd!
  autocmd InsertEnter * call plug#load('rainbow')
        \| autocmd! load_rainbow
        \| call rainbow_main#toggle()
augroup END

" VIM-GITGUTTER
augroup load_vim_gitgutter
  autocmd!
  autocmd BufReadPost * call plug#load('vim-gitgutter')
        \| autocmd! load_vim_gitgutter
        \| call gitgutter#buffer_enable()
augroup END

" TERMINUS
augroup load_terminus
  autocmd!
  autocmd InsertEnter * call plug#load('terminus')
        \| autocmd! load_terminus
augroup END

" CONTEXT.VIM
augroup load_context_vim
  autocmd!
  autocmd BufReadPost * call plug#load('context.vim')
        \| autocmd! load_context_vim
        \| ContextEnable
augroup END

" VIM-WHICH-KEY
nnoremap <silent> <leader> :<c-u>WhichKey '\'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey  '<Space>'<CR>

" NERDTREE
let g:NERDTreeShowHidden=1
nnoremap <C-n> <CMD>NERDTreeToggle<CR>

" QUICKRUN
nnoremap <leader>rr <CMD>QuickRun<CR>

" FZF FZF.VIM
nnoremap <leader>fb <CMD>Buffers<CR>
nnoremap <leader>fc <CMD>Colors<CR>
nnoremap <leader>fr <CMD>History<CR>
nnoremap <leader>fw <CMD>Rg<CR>
nnoremap <leader>fs <CMD>BLines<CR>
nnoremap <leader>fS <CMD>Lines<CR>
nnoremap <leader>ff <CMD>Files<CR>
nnoremap <leader>fF <CMD>Files ~/<CR>

" VIM-EASYMOTION
let g:EasyMotion_do_mapping=0
nnoremap <leader>gl <Plug>(easymotion-bd-jk)
nnoremap <leader>gw <Plug>(easymotion-bd-w)
