" REFERENCE
" https://github.com/junegunn/vim-plug/wiki/tips
" https://github.com/skywind3000/vim-init
" https://github.com/wklken/k-vim
" https://github.com/amix/vimrc
" https://gitee.com/mirrorvim/vim-fast/blob/master/vimrc-no-plug
" https://github.com/chenxuan520/vim-fast

" OPTION
filetype on
filetype plugin on
filetype indent on
syntax enable
syntax on
set autoread
set backspace=indent,eol,start
set ruler
set number
set relativenumber
set cursorline
set cursorcolumn
set colorcolumn=80
set splitbelow
set splitright
set clipboard^=unnamed,unnamedplus
set nowrap
set showtabline=2
set laststatus=2
set wildmenu
set autoindent
set cindent
set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smarttab
set hlsearch
set incsearch
set ignorecase
set smartcase
set nobackup
set noswapfile
set notermguicolors
set background=dark
set timeoutlen=200
let g:vim_indent_cont=&sw
colorscheme desert

" KEYBINDING
let mapleader='\'
let maplocalleader=' '
nnoremap <leader>CE <cmd>edit $MYVIMRC<cr>
nnoremap <leader>CR <cmd>source $MYVIMRC<cr>
inoremap jk <esc>
vnoremap jk <esc>
cnoremap jk <c-c>

" BUILTIN PLUGIN
let g:loaded_getscriptPlugin=1
let g:loaded_gzip=1
let g:loaded_logiPat=1
let g:loaded_manpager=1
let g:loaded_matchit=1
let g:loaded_matchparen=1
let g:loaded_netrwPlugin=1
let g:loaded_rrhelper=1
let g:loaded_spellfile=1
let g:loaded_tarPlugin=1
let g:loaded_tohtml=1
let g:loaded_vimballPlugin=1
let g:loaded_zipPlugin=1

" AUTOCMD
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line('$') | exe "normal! g'\"" | endif
autocmd BufEnter * setlocal formatoptions-=r formatoptions-=c formatoptions-=o
autocmd BufWinEnter * if getfsize(expand('%')) > 1048576 | syntax clear | endif
autocmd FileType python setlocal shiftwidth=4 tabstop=4 softtabstop=4
autocmd FileType help noremap <buffer> q :bd<CR>

" VIM-PLUG
if empty(glob('~/.vim/autoload/plug.vim'))
  silent execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd BufWinEnter * PlugInstall --sync | source $MYVIMRC
endif
autocmd BufWinEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) > 0 | PlugInstall --sync | source $MYVIMRC | endif
call plug#begin()
Plug 'LunarWatcher/auto-pairs', { 'on': [] }
Plug 'tpope/vim-commentary', { 'on': [] }
call plug#end()

" AUTO-PAIRS
augroup LOAD_AUTO_PAIRS
  autocmd!
  autocmd InsertEnter * call plug#load('auto-pairs')
    \| autocmd! LOAD_AUTO_PAIRS
    \| call autopairs#AutoPairsTryInit()
augroup end

" VIM-COMMENTARY
augroup LOAD_VIM_COMMENTARY
  autocmd!
  autocmd BufReadPost * call plug#load('vim-commentary')
    \| autocmd! LOAD_VIM_COMMENTARY
augroup END
