#!/usr/bin/env sh

### GENERAL ###

BAR=(
  potision=top
  height=24
  color=0xff1e1e2e
  shadow=off
  stiky=on
  padding_right=2
  padding_left=2
  margin=0
)
sketchybar --bar "${BAR[@]}"

DEFAULT=(
  updates=when_shown
  icon.font="SF Pro:Bold:11.0"
  icon.color=0xffcad3f5
  icon.padding_left=3
  icon.padding_right=3
  label.font="SF Pro:Semibold:11.0"
  label.color=0xffcad3f5
  label.padding_left=3
  label.padding_right=3
  padding_left=2
  padding_right=2
  background_height=24
  background.corner_radius=8
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=8
  popup.background.border_color=0xffcad3f5
  popup.background.color=0xff1e1e2e
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)
sketchybar --default "${DEFAULT[@]}"

### LEFT ###

## APPLE LOGO ##
APPLE_LOGO=(
  icon=􀣺
  icon.font="SF Pro:Bold:16.0"
  icon.color=0xffa6da95
  icon.padding_left=8
  icon.padding_right=8
  padding_right=8
  label.drawing=off
  background.color=0x603c3e4f
  background.border_color=0x60494d64
  popup.height=35
  click_script="sketchybar --set \$NAME popup.drawing=toggle"
)
sketchybar --add item apple.logo left --set apple.logo "${APPLE_LOGO[@]}"

PREFERENCE=(
  icon=􀺽
  label="System Preferences"
  click_script="open -a 'System Preferences'; sketchybar --set apple.logo popup.drawing=off"
)
sketchybar --add item apple.preference popup.apple.logo --set apple.preference "${PREFERENCE[@]}"

ACTIVITY=(
  icon=􀒓
  label="Activity Monitor"
  click_script="open -a 'Activity Monitor'; sketchybar --set apple.logo popup.drawing=off"
)
sketchybar --add item apple.activity popup.apple.logo --set apple.activity "${ACTIVITY[@]}"

LOCK=(
  icon=􀒳
  label="Lock Screen"
  click_script="pmset displaysleepnow; sketchybar --set apple.logo popup.drawing=off"
)
sketchybar --add item apple.lock popup.apple.logo --set apple.lock "${LOCK[@]}"

## WORKSPACE ##
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  SPACE=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=8
    icon.padding_right=8
    padding_left=2
    padding_right=2
    label.drawing=off
    background.color=0x603c3e4f
    background.border_color=0x60494d64
    click_script="yabai -m space --focus $sid"
    script='
      if [[ "$SELECTED" == "true" ]]; then
        sketchybar --set "$NAME" background.drawing="$SELECTED" icon.color=0xffed8796
      else
        sketchybar --set "$NAME" background.drawing="$SELECTED" icon.color=0xffcad3f5
      fi
    '
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${SPACE[@]}" --subscribe space.$sid mouse.clicked
done

## SEPARATOR ##
SEPARATOR=(
  icon=􀆊
  icon.color=0xffcad3f5
  padding_left=10
  padding_right=10
  label.drawing=off
  display=active
  click_script='yabai -m space --create'
)
sketchybar --add item separator left --set separator "${SEPARATOR[@]}" --subscribe separator space_window_change

## WINDOW TITLE ##
WINDOW_TITLE=(
  icon.drawing=off
  label.font="SF Pro:Black:12.0"
  display=active
  background.color=0x603c3e4f
  background.border_color=0x60494d64
  label.padding_left=8
  label.padding_right=8
  click_script="open -a 'Mission Control'"
  script='
    if [ "$SENDER" = "front_app_switched" ]; then
      sketchybar --set "$NAME" label="$INFO"
    fi
  '
)
sketchybar --add item window_title left --set window_title "${WINDOW_TITLE[@]}" --subscribe window_title front_app_switched

### RIGHT ###

## DATETIME ##
DATETIME=(
  icon=􀧞
  update_freq=10
  background.color=0x603c3e4f
  background.border_color=0x60494d64
  icon.padding_left=8
  label.padding_right=8
  script="
    sketchybar --set \"\$NAME\" label=\"\$(date '+%Y-%m-%d %H:%M')\"
  "
)
sketchybar --add item datetime right --set datetime "${DATETIME[@]}"

## BATTERY ##
BATTERY=(
  background.color=0x603c3e4f
  background.border_color=0x60494d64
  icon.padding_left=8
  label.padding_right=8
  update_freq=120
  script="
    PERCENTAGE=\"\$(pmset -g batt | grep -Eo \"\d+%\" | cut -d% -f1)\"
    CHARGING=\"\$(pmset -g batt | grep 'AC Power')\"
    if [ -z \"\$PERCENTAGE\" ]; then
      exit 0
    fi
    case \"\$PERCENTAGE\" in
      9[0-9]|100)
        ICON=\"􀛨\"
        COLOR=0xffa6da95
        ;;
      [6-8][0-9])
        ICON=\"􀺸\"
        COLOR=0xffeed49f
        ;;
      [3-5][0-9])
        ICON=\"􀺶\"
        COLOR=0xfff5a97f
        ;;
      [1-2][0-9])
        ICON=\"􀛩\"
        COLOR=0xffed8796
        ;;
      *)
        ICON=\"􀛪\"
        COLOR=0xffed8796
        ;;
    esac
    if [[ -n \"\$CHARGING\" ]]; then
      ICON=\"􀢋\"
      COLOR=0xffa6da95
    fi
    sketchybar --set \"\$NAME\" icon=\"\$ICON\" label=\"\${PERCENTAGE}%\" icon.color=\"\$COLOR\"
  "
)
sketchybar --add item battery right --set battery "${BATTERY[@]}" --subscribe battery system_woke power_source_change

## VOLUME ##
VOLUME=(
  icon.padding_left=8
  label.padding_right=8
  background.color=0x603c3e4f
  background.border_color=0x60494d64
  script="
    if [ \"\$SENDER\" = \"volume_change\" ]; then
      VOL=\"\$INFO\"
      case \"\$VOL\" in
      [8-9][0-9]|100)
        ICON=\"􀊩\"
        COLOR=0xffed8796
        ;;
      [5-8][0-9])
        ICON=\"􀊧\"
        COLOR=0xfff5a97f
        ;;
      [3-5][0-9])
        ICON=\"􀊥\"
        COLOR=0xffeed49f
        ;;
      [1-9]|[1-3][0-9])
        ICON=\"􀊡\"
        COLOR=0xffcad3f5
        ;;
      *)
        ICON=\"􀊣\"
        COLOR=0xffc6a0f6
        ;;
      esac
      sketchybar --set \"\$NAME\" icon=\"\$ICON\" icon.color=\"\$COLOR\" label=\"\$VOL%\"
    fi
  "
)
sketchybar --add -item volume right --set volume "${VOLUME[@]}" --subscribe volume volume_change

## RAM ###
RAM=(
  icon.padding_left=8
  label.padding_right=8
  background.color=0x603c3e4f
  background.border_color=0x60494d64
  update_freq=3
  script="
    RAM_PERCENTAGE=\$(memory_pressure | grep \"System-wide memory free percentage:\" | awk '{print 100-\$5\"\"}')
    case \"\$RAM_PERCENTAGE\" in
      9[0-9]|100)
        ICON=􀐟
        COLOR=0xffed8796
        ;;
      [6-8][0-9])
        ICON=􀐟
        COLOR=0xfff5a97f
        ;;
      [3-5][0-9])
        ICON=􀐟
        COLOR=0xffeed49f
        ;;
      *)
        ICON=􀐞
        COLOR=0xffa6da95
        ;;
    esac
    sketchybar --set \"\$NAME\" label=\"\$RAM_PERCENTAGE%\" icon=\"\$ICON\" icon.color=\"\$COLOR\"
  "
)
sketchybar --add item ram right --set ram "${RAM[@]}"

## CPU ##
CPU=(
  icon.padding_left=8
  label.padding_right=8
  background.color=0x603c3e4f
  background.border_color=0x60494d64
  update_freq=3
  script="
    CPU_PERCENTAGE=\$(top -l 2 | grep -E \"^CPU\" | tail -1 | awk '{ printf(\"%d\", \$3 + \$5) }')
    case \"\$CPU_PERCENTAGE\" in
      9[0-9]|100)
        ICON=􀧓
        COLOR=0xffed8796
        ;;
      [6-8][0-9])
        ICON=􀧓
        COLOR=0xfff5a97f
        ;;
      [3-5][0-9])
        ICON=􀧓
        COLOR=0xffeed49f
        ;;
      *)
        ICON=􀫥
        COLOR=0xffa6da95
        ;;
    esac
    sketchybar --set \$NAME label=\"\$CPU_PERCENTAGE%\" icon=\"\$ICON\" icon.color=\"\$COLOR\"
  "
)
sketchybar --add item cpu right --set cpu "${CPU[@]}"

sketchybar --update
