#!/usr/bin/env sh

# PLUGIN DIR
PLUGIN_DIR="$CONFIG_DIR/plugins"

# BAR
bar=(
  height=24
  blur_radius=0
  position=bottom
  padding_left=0
  padding_right=0
  margin=0
  corner_radius=0
  color=0xff000000
  border_width=0
  border_color=0xff000000
)
sketchybar --bar "${bar[@]}"

# DEFAULT
default=(
  updates=when_shown
  drawing=on
  cache_scripts=on
  icon.font="SF Pro:Bold:12.0"
  icon.color=0xffffffff
  icon.highlight_color=0xff808080
  icon.padding_left=0
  icon.padding_right=0
  lebel.font="SF Pro:Bold:12.0"
  label.color=0xffffffff
  label.padding_left=0
  label.padding_right=0
)
sketchybar --default "${default[@]}"

# APPLE LOGO
sketchybar -m --add item logo left \
              --set logo icon= \
                         icon.padding_left=8 \
                         icon.padding_right=8 \
                         background.color=0xff007aff \
                         background.height=24 \
                         background.padding_right=0 \
                         background.padding_left=0

# WINDOW SPACE
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
SPACE=()
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  SPACE+=(space.$sid)
  sketchybar --add space space.$sid left \
             --set space.$sid associated_space=$sid \
                              icon=${SPACE_ICONS[i]} \
                              icon.padding_left=10 \
                              icon.padding_right=10 \
                              icon.highlight_color=0xff30D158 \
                              background.padding_left=0 \
                              background.padding_right=0 \
                              background.color=0xff000000 \
                              background.drawing=on \
                              background.height=24 \
                              label.drawing=off \
                              click_script="yabai -m space --focus $sid"
done

# RAM
sketchybar -m --add item ram right --set ram script="$PLUGIN_DIR/ram.sh" background.color=0xff000000 background.height=24 update_freq=1
sketchybar -m --add item ram_logo right --set ram_logo icon=RAM icon.padding_left=8 icon.padding_right=8 background.color=0xff5856D6 background.height=24

# CPU
sketchybar -m --add item cpu right --set cpu script="$PLUGIN_DIR/cpu.sh" background.color=0xff000000 background.height=24 update_freq=1
sketchybar -m --add item cpu_logo right --set cpu_logo icon=CPU icon.padding_left=8 icon.padding_right=8 background.color=0xffFF2D55 background.height=24

# UPDATE
sketchybar -m --update
echo "sketchybar configuration loaded..."
