#!/bin/zsh

### BASIC SETTING
PLUGIN_DIR=$CONFIG_DIR/plugins
FONT_SANS_SERIF="SF Pro:Semibold"
FONT_MONOSPACE="JetBrainsMono Nerd Font:Regular"

default=(
  updates=when_shown
  icon.font="$FONT_MONOSPACE:14.0"
  label.font="$FONT_SANS_SERIF:14.0"
  icon.color=0xffabb2bf
  label.color=0xffabb2bf
  icon.highlight_color=0xffe06c75
  icon.padding_left=8
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=8
  background.corner_radius=5
  background.height=30
  popup.background.border_width=2
  popup.background.corner_radius=5
  popup.background.border_color=0xffabb2bf
  popup.background.color=0xff1b1f27
  popup.height=28
)
sketchybar --default "${default[@]}"

bar=(
  height=36
  blur_radius=0
  color=0xff1b1f27
  position=bottom
  padding_left=4
  padding_right=4
  margin=0
  corner_radius=0
)
sketchybar --bar "${bar[@]}"

sketchybar --add event window_focus
sketchybar --add event title_change
sketchybar --add event skhd_mode_change

### LEFT

# APPLE ICON
apple=(
  icon=
  label.drawing=off
  icon.color=0xff98c379
  icon.padding_left=9
  icon.padding_right=9
  background.padding_right=4
  background.padding_left=4
)
sketchybar --add item apple left
sketchybar --set apple "${apple[@]}" 

# SPACE
spaces=("1" "2" "3" "4" "5" "6" "7" "8" "9" "0")
for name in ${spaces[@]}; do
  sid=${name:0:1}
  space=(
    space=$sid
    icon=$name
    icon.padding_left=6
    icon.padding_right=6
    icon.highlight_color=0xffe06c75
    background.padding_left=0
    background.padding_right=0
    background.color=0xff373b43
    background.drawing=off
    script=$PLUGIN_DIR/space.sh
    label.drawing=off
    icon.font=$FONT_SANS_SERIF:14.0
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space.$sid left
  sketchybar --set space.$sid "${space[@]}"
done

# TITLE
title=(
  icon=
  icon.padding_left=8
  icon.padding_right=8
  icon.color=0xff61afef
  script=$PLUGIN_DIR/title.sh
)
sketchybar --add item title left
sketchybar --set title "${title[@]}"
sketchybar --subscribe title window_focus title_change front_app_switched space_change

### RIGHT

# TIME
time=(
  update_freq=5
  icon=
  icon.color=0xffde98fd
  script=$PLUGIN_DIR/time.sh
)
sketchybar --add item time right
sketchybar --set time "${time[@]}"

# DATE
date=(
  update_freq=5
  icon=󰸘
  icon.color=0xffebcb8b
  script=$PLUGIN_DIR/date.sh
)
sketchybar --add item date right
sketchybar --set date "${date[@]}"

# BATTERY
battery=(
  update_freq=120
  script=$PLUGIN_DIR/battery.sh
  icon.color=0xff7eca9c
  label.drawing=on
)
sketchybar --add item battery right
sketchybar --set battery "${battery[@]}"
sketchybar --subscribe battery system_woke power_source_change

# MEMORY
memory=(
  icon=
  icon.font="$FONT_MONOSPACE:14.0"
  update_freq=3
  script=$PLUGIN_DIR/memory.sh
)
sketchybar --add item memory right
sketchybar --set memory "${memory[@]}"

# CPU
cpu=(
  icon=
  icon.font="$FONT_MONOSPACE:14.0"
  update_freq=3
  script=$PLUGIN_DIR/cpu.sh
)
sketchybar --add item cpu right
sketchybar --set cpu "${cpu[@]}"

### Force all scripts to run the first time (never do this in a script)
sketchybar --update
