#!/bin/zsh
### DEPENDENCY: sf-symbols

### BASIC SETTING
PLUGIN_DIR=$CONFIG_DIR/plugins

default=(
  updates=when_shown
  icon.font="SF Pro:Semibold:13.0"
  label.font="SF Pro:Semibold:13.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.highlight_color=0xff3c3e4f
  icon.padding_left=2
  icon.padding_right=2
  label.padding_left=4
  label.padding_right=4
  background.corner_radius=4
  background.height=24
  popup.background.border_width=2
  popup.background.corner_radius=4
  popup.background.border_color=0xffffffff
  popup.background.color=0xff000000
  popup.height=24
)
sketchybar --default "${default[@]}"

bar=(
  height=24
  blur_radius=0
  color=0xff000000
  position=bottom
  padding_left=4
  padding_right=4
  margin=0
  corner_radius=0
)
sketchybar --bar "${bar[@]}"

sketchybar --add event window_focus
sketchybar --add event title_change
sketchybar --add event skhd_mode_change

### LEFT

# APPLE ICON
apple=(
  icon=􀣺
  label.drawing=off
  icon.color=0xffb3e1a7
  icon.padding_left=8
  icon.padding_right=8
  background.padding_right=4
  background.padding_left=4
)
sketchybar --add item apple left
sketchybar --set apple "${apple[@]}" 

# SPACE
spaces=("1" "2" "3" "4" "5" "6" "7" "8" "9" "0")
for name in ${spaces[@]}; do
  sid=${name:0:1}
  space=(
    space=$sid
    icon=$name
    icon.padding_left=8
    icon.padding_right=8
    icon.highlight_color=0xff3c3e4f
    background.padding_left=0
    background.padding_right=0
    background.color=0xff92b3f5
    background.drawing=off
    script=$PLUGIN_DIR/space.sh
    label.drawing=off
    icon.font="SF Pro:Semibold:13.0"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space.$sid left
  sketchybar --set space.$sid "${space[@]}"
done

# TITLE
title=(
  icon=􀁵
  icon.padding_left=8
  icon.padding_right=8
  icon.color=0xff92b3f5
  script=$PLUGIN_DIR/title.sh
)
sketchybar --add item title left
sketchybar --set title "${title[@]}"
sketchybar --subscribe title window_focus title_change front_app_switched space_change

### RIGHT

# TIME
time=(
  update_freq=5
  icon=􀐫
  icon.color=0xfff5e3b5
  icon.padding_left=4
  icon.padding_right=2
  label.padding_left=2
  label.padding_right=4
  script=$PLUGIN_DIR/time.sh
)
sketchybar --add item time right
sketchybar --set time "${time[@]}"

# DATE
date=(
  update_freq=5
  icon=􀉉
  icon.color=0xff92b3f5
  icon.padding_left=4
  icon.padding_right=2
  label.padding_left=2
  label.padding_right=4
  script=$PLUGIN_DIR/date.sh
)
sketchybar --add item date right
sketchybar --set date "${date[@]}"

# BATTERY
battery=(
  update_freq=120
  script=$PLUGIN_DIR/battery.sh
  icon.color=0xffb3e1a7
  icon.padding_left=4
  icon.padding_right=2
  label.padding_left=2
  label.padding_right=4
  label.drawing=on
)
sketchybar --add item battery right
sketchybar --set battery "${battery[@]}"
sketchybar --subscribe battery system_woke power_source_change

# MEMORY
memory=(
  icon=􀫦
  icon.color=0xfff69c5e
  icon.font="SF Pro:Semibold:13.0"
  icon.padding_left=4
  icon.padding_right=2
  label.padding_left=2
  label.padding_right=4
  update_freq=3
  script=$PLUGIN_DIR/memory.sh
)
sketchybar --add item memory right
sketchybar --set memory "${memory[@]}"

# CPU
cpu=(
  icon=􀫥
  icon.color=0xffe48fa8
  icon.font="SF Pro:Semibold:13.0"
  icon.padding_left=4
  icon.padding_right=2
  label.padding_left=2
  label.padding_right=4
  update_freq=3
  script=$PLUGIN_DIR/cpu.sh
)
sketchybar --add item cpu right
sketchybar --set cpu "${cpu[@]}"

### Force all scripts to run the first time (never do this in a script)
sketchybar --update
