#!/bin/sh

### PLUGIN DIRECTORY
PLUGIN_DIR=$CONFIG_DIR/plugin

### DEFAULT
default=(
  updates=when_shown
  icon.font="JetBrainsMono Nerd Font:Bold:14.0"
  label.font="JetBrainsMono Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.highlight_color=0xffe48fa8
  icon.padding_left=8
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=8
  background.corner_radius=5
  background.height=30
  popup.background.border_width=2
  popup.background.corner_radius=5
  popup.background.border_color=0xff007aff
  popup.background.color=0xff000000
  popup.height=30
)
sketchybar --default "${default[@]}"

### BAR
bar=(
  blur_radius=0
  position=bottom
  height=36
  color=0xff000000
  padding_left=4
  padding_right=4
  margin=0
  corner_radius=0
)
sketchybar --bar "${bar[@]}"

### EVENT
sketchybar --add event window_focus
sketchybar --add event title_change
sketchybar --add event yabai_mode

### LEFT

## APPLE LOGO
apple=(
  icon=
  label.drawing=off
  icon.color=0xff007aff
  icon.padding_left=4
  icon.padding_right=4
  background.padding_right=4
  background.padding_left=4
  click_script="sketchybar --set \"\$NAME\" popup.drawing=toggle"
)
sketchybar --add item apple left --set apple "${apple[@]}"
appleterminal=(
  icon=
  label="Terminal"
  label.font="SF Pro:Bold:14.0"
  click_script="open -n '/System/Applications/Utilities/Terminal.app'; $POPUP_CLOSE"
)
sketchybar --add item apple.terminal popup.apple --set apple.terminal "${appleterminal[@]}"
appleprefs=(
  icon=
  label="Preferences"
  label.font="SF Pro:Bold:14.0"
  click_script="open -a 'System Preferences'; $POPUP_CLOSE"
)
sketchybar --add item apple.prefs popup.apple --set apple.prefs "${appleprefs[@]}"
appleactivity=(
  icon=󰍹
  label="Activity"
  label.font="SF Pro:Bold:14.0"
  click_script="open -a 'Activity Monitor'; $POPUP_CLOSE"
)
sketchybar --add item apple.activity popup.apple --set apple.activity "${appleactivity[@]}"
applelock=(
  icon=
  label="Lock Screen"
  label.font="SF Pro:Bold:14.0"
  click_script="$POPUP_CLOSE; pmset displaysleepnow"
)
sketchybar --add item apple.lock popup.apple --set apple.lock "${applelock[@]}"

## SPACE
SPACEICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "0")
for i in "${!SPACEICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    background.color=0xff007aff
    background.drawing=off
    background.padding_left=0
    background.padding_right=0
    click_script="yabai -m space --focus $sid"
    icon="${SPACEICONS[i]}"
    icon.font="SF Pro:Bold:14.0"
    icon.highlight_color=0xffffffff
    icon.padding_left=8
    icon.padding_right=8
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    space="$sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

## FRONT APP
front_app=(
  icon=
  icon.font="JetBrainsMono Nerd Font:Bold:14.0"
  icon.color=0xff007aff
  label.font="SF Pro:Bold:14.0"
  label.color=0xffffffff
  padding_left=1
  padding_right=1
  script=$PLUGIN_DIR/front_app.sh
)
sketchybar --add item front_app left --set front_app "${front_app[@]}" --subscribe front_app front_app_switched

### RIGHT

## DATETIME
datetime=(
  icon=󰸘
  icon.color=0xffffd60a
  icon.padding_left=1
  icon.padding_right=1
  label.font="SF Pro:Bold:14"
  script=$PLUGIN_DIR/datetime.sh
  update_freq=60
)
sketchybar --add item datetime right --set datetime "${datetime[@]}"

## BATTERY
battery=(
  icon.font="JetBrainsMono Nerd Font:Bold:14.0"
  icon.padding_left=1
  icon.padding_right=1
  label.font="SF Pro:Bold:14"
  update_freq=20
  script=$PLUGIN_DIR/battery.sh
)
sketchybar --add item battery right --set battery "${battery[@]}"

## MEMORY
memory=(
  icon=
  icon.font="JetBrainsMono Nerd Font:Bold:14.0"
  icon.padding_left=1
  icon.padding_right=1
  label.font="SF Pro:Bold:14"
  update_freq=3
  script=$PLUGIN_DIR/memory.sh
)
sketchybar --add item memory right --set memory "${memory[@]}"

## CPU
cpu=(
  icon=
  icon.font="JetBrainsMono Nerd Font:Bold:14.0"
  icon.padding_left=1
  icon.padding_right=1
  label.font="SF Pro:Bold:14"
  update_freq=3
  script=$PLUGIN_DIR/cpu.sh
)
sketchybar --add item cpu right --set cpu "${cpu[@]}"

### Force all scripts to run the first time (never do this in a script)
sketchybar --update
