#!/usr/bin/bash

# MONITORS
monitor=,highres,auto,1.2

# AUTOSTART
exec-once = xclip
exec-once = copyq --start-server
exec-once = nm-applet
exec-once = ibus-daemon -drxR
exec-once = waybar -c /home/cya/.config/hypr/waybar/config.jsonc -s /home/cya/.config/hypr/waybar/style.css
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprpaper -c /home/cya/.config/hypr/hyprpaper.conf

# ENVIRONMENT VARIABLE
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
# env = XDG_CURRENT_DESKTOP,Hyprland
# env = XDG_SESSION_TYPE,wayland
# env = XDG_SESSION_DESKTOP,Hyprland
# env = EDITOR,vim
# env = MOZ_ENABLE_WAYLAND,1
# env = GDK_BACKEND,"wayland,x11"
# env = QT_QPA_PLATFORM,"xcb;wayland"
# env = QT_QPA_PLATFORMTHEME,qt5ct
# env = QT_AUTO_SCREEN_SCALE_FACTOR,1
# env = QT_SCALE_FACTOR,1
# env = GDK_DPI_SCALE,1

# UI
general { 
gaps_in = 4
gaps_out = 4
border_size = 2
col.active_border = 0xff89b4fa
col.inactive_border = 0xffa6e3a1
resize_on_border = false 
allow_tearing = false
layout = dwindle
}

# DECORATION
decoration {
rounding = 4
active_opacity = 1.0
inactive_opacity = 0.85
drop_shadow = true
shadow_range = 0
shadow_render_power = 3
col.shadow = rgba(1a1a1aee)
blur {
enabled = true
size = 3
passes = 1
vibrancy = 0.1696
}
}

# ANIMATION
animations {
enabled = true
bezier = myBezier, 0.05, 0.9, 0.1, 1.05
animation = windows, 1, 7, myBezier
animation = windowsOut, 1, 7, default, popin 80%
animation = border, 1, 10, default
animation = borderangle, 1, 8, default
animation = fade, 1, 7, default
animation = workspaces, 1, 6, default
}

# LAYOUT
dwindle {
pseudotile = true
preserve_split = true
}
master {
new_status = master
}

# MISCELLANEOUS
misc { 
force_default_wallpaper = -1
disable_hyprland_logo = false
}

# INPUT
input {
kb_layout = us
kb_variant =
kb_model =
kb_options =
kb_rules =
follow_mouse = 1
sensitivity = 0
touchpad {
disable_while_typing = 1
natural_scroll = true
tap-to-click = true
}
}
gestures {
workspace_swipe = true
}
xwayland {
force_zero_scaling = true
}
device {
name = epic-mouse-v1
sensitivity = -0.5
}

# KEYBINDING
$Mod4 = SUPER
$Mod1 = ALT
bind = $Mod1, Return, exec, kitty
bind = $Mod1 SHIFT, Q, killactive,
bind = $Mod1 SHIFT, E, exit,
bind = $Mod1, f, togglefloating,
bind = $Mod1, space, exec, wofi --show run
bind = $Mod1, l, resizeactive, 50 0
bind = $Mod1, h, resizeactive, -50 0
bind = $Mod1, j, cyclenext, next
bind = $Mod1, k, cyclenext, prev
bind = $Mod1, 1, workspace, 1
bind = $Mod1, 2, workspace, 2
bind = $Mod1, 3, workspace, 3
bind = $Mod1, 4, workspace, 4
bind = $Mod1, 5, workspace, 5
bind = $Mod1, 6, workspace, 6
bind = $Mod1, 7, workspace, 7
bind = $Mod1, 8, workspace, 8
bind = $Mod1, 9, workspace, 9
bind = $Mod1, 0, workspace, 10
bind = $Mod1 SHIFT, 1, movetoworkspace, 1
bind = $Mod1 SHIFT, 2, movetoworkspace, 2
bind = $Mod1 SHIFT, 3, movetoworkspace, 3
bind = $Mod1 SHIFT, 4, movetoworkspace, 4
bind = $Mod1 SHIFT, 5, movetoworkspace, 5
bind = $Mod1 SHIFT, 6, movetoworkspace, 6
bind = $Mod1 SHIFT, 7, movetoworkspace, 7
bind = $Mod1 SHIFT, 8, movetoworkspace, 8
bind = $Mod1 SHIFT, 9, movetoworkspace, 9
bind = $Mod1 SHIFT, 0, movetoworkspace, 10
bind = $Mod1 SHIFT, L, exec, hyprlock
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-
bind = , PRINT, exec, hyprshot -m output
