#!/bin/sh

lalt - return : open -n /System/Applications/Utilities/Terminal.app
lalt - h : yabai -m window --focus west || yabai -m display --focus west
lalt - j : yabai -m window --focus south || yabai -m display --focus south
lalt - k : yabai -m window --focus north || yabai -m display --focus north
lalt - l : yabai -m window --focus east || yabai -m display --focus east
lalt - f : yabai -m window --toggle native-fullscreen
lshift + lalt - s : yabai -m window --toggle split
lshift + lalt - h : yabai -m window --swap west || $(yabai -m window --display west; yabai -m display --focus west)
lshift + lalt - j : yabai -m window --swap south || $(yabai -m window --display south; yabai -m display --focus south)
lshift + lalt - k : yabai -m window --swap north || $(yabai -m window --display north; yabai -m display --focus north)
lshift + lalt - l : yabai -m window --swap east || $(yabai -m window --display east; yabai -m display --focus east)
lctrl + lalt - h : yabai -m window --resize right:-100:0 || yabai -m window --resize left:-100:0
lctrl + lalt - j : yabai -m window --resize bottom:0:100 || yabai -m window --resize top:0:100
lctrl + lalt - k : yabai -m window --resize bottom:0:-100 || yabai -m window --resize top:0:-100
lctrl + lalt - l : yabai -m window --resize right:100:0 || yabai -m window --resize left:100:0
lshift + lalt - r : yabai --restart-service || skhd --restart-service
lshift + lalt - e : yabai --stop-service || skhd --stop-service
lshift + lalt - f : yabai -m window --toggle float
lalt - 1 : yabai -m space --focus 1
lalt - 2 : yabai -m space --focus 2
lalt - 3 : yabai -m space --focus 3
lalt - 4 : yabai -m space --focus 4
lalt - 5 : yabai -m space --focus 5
lalt - 6 : yabai -m space --focus 6
lalt - 7 : yabai -m space --focus 7
lalt - 8 : yabai -m space --focus 8
lalt - 9 : yabai -m space --focus 9
lalt - 0 : yabai -m space --focus 10
lshift + lalt - 1 : yabai -m window --space 1
lshift + lalt - 2 : yabai -m window --space 2
lshift + lalt - 3 : yabai -m window --space 3
lshift + lalt - 4 : yabai -m window --space 4
lshift + lalt - 5 : yabai -m window --space 5
lshift + lalt - 6 : yabai -m window --space 6
lshift + lalt - 7 : yabai -m window --space 7
lshift + lalt - 8 : yabai -m window --space 8
lshift + lalt - 9 : yabai -m window --space 9
lshift + lalt - 0 : yabai -m window --space 10
