#!/usr/bin/env sh

lcmd - return : open -n /System/Applications/Utilities/Terminal.app
lcmd - 1 : yabai -m space --focus 1
lcmd - 2 : yabai -m space --focus 2
lcmd - 3 : yabai -m space --focus 3
lcmd - 4 : yabai -m space --focus 4
lcmd - 5 : yabai -m space --focus 5
lcmd - 6 : yabai -m space --focus 6
lcmd - 7 : yabai -m space --focus 7
lcmd - 8 : yabai -m space --focus 8
lcmd - 9 : yabai -m space --focus 9
lcmd - 0 : yabai -m space --focus 10
lcmd - h : yabai -m window --focus west || yabai -m display --focus west
lcmd - j : yabai -m window --focus south || yabai -m display --focus south
lcmd - k : yabai -m window --focus north || yabai -m display --focus north
lcmd - l : yabai -m window --focus east || yabai -m display --focus east
lcmd - f : yabai -m window --toggle native-fullscreen
lshift + lcmd - s : yabai -m window --toggle split
lshift + lcmd - h : yabai -m window --swap west || $(yabai -m window --display west; yabai -m display --focus west)
lshift + lcmd - j : yabai -m window --swap south || $(yabai -m window --display south; yabai -m display --focus south)
lshift + lcmd - k : yabai -m window --swap north || $(yabai -m window --display north; yabai -m display --focus north)
lshift + lcmd - l : yabai -m window --swap east || $(yabai -m window --display east; yabai -m display --focus east)
lctrl + lcmd - h : yabai -m window --resize right:-100:0 || yabai -m window --resize left:-100:0
lctrl + lcmd - j : yabai -m window --resize bottom:0:100 || yabai -m window --resize top:0:100
lctrl + lcmd - k : yabai -m window --resize bottom:0:-100 || yabai -m window --resize top:0:-100
lctrl + lcmd - l : yabai -m window --resize right:100:0 || yabai -m window --resize left:100:0
lshift + lcmd - r : yabai --restart-service || skhd --restart-service
lshift + lcmd - e : yabai --stop-service || skhd --stop-service
lshift + lcmd - space : yabai -m window --toggle float
lshift + lcmd - 1 : yabai -m window --space 1
lshift + lcmd - 2 : yabai -m window --space 2
lshift + lcmd - 3 : yabai -m window --space 3
lshift + lcmd - 4 : yabai -m window --space 4
lshift + lcmd - 5 : yabai -m window --space 5
lshift + lcmd - 6 : yabai -m window --space 6
lshift + lcmd - 7 : yabai -m window --space 7
lshift + lcmd - 8 : yabai -m window --space 8
lshift + lcmd - 9 : yabai -m window --space 9
lshift + lcmd - 0 : yabai -m window --space 10
