window/bar:
  providers: ['self']
  width: '{{ self.args.MONITOR_WIDTH }}'
  height: '40'
  position_x: '{{ self.args.MONITOR_X }}'
  position_y: '{{ self.args.MONITOR_Y }}'
  z_order: 'normal'
  shown_in_taskbar: true
  resizable: false
  global_styles: |
    @import "https://www.nerdfonts.com/assets/css/webfont.css";
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
    height: 100%;
    color: rgb(255 255 255 / 90%);
    font-family: JetBrainsMono Nerd Font Bold, Consolas, ui-monospace, monospace;
    font-size: 12px;
    padding: 4px 4px;
    border-bottom: 0px solid rgb(255 255 255 / 5%);;
    background: linear-gradient(rgb(0 0 0 / 90%), rgb(5 2 20 / 85%));
    i {
      color: rgb(115 130 175 / 95%);
      margin-right: 4px;
    }
  group/left:
    styles: |
      display: flex;
      align-items: center;
    template/logo:
      styles: |
        margin-right: 0px;
        margin-left: 8px;
      template: |
        <i class="nf nf-fa-windows"></i>
    template/glazewm_workspaces:
      styles: |
        display: flex;
        align-items: center;
        .workspace {
          background: rgb(255 255 255 / 5%);
          margin-right: 0px;
          margin-left: 0px;
          padding: 4px 4px;
          color: rgb(255 255 255 / 90%);
          border: none;
          border-radius: 4px;
          cursor: pointer;
          &.displayed {
            background: rgb(255 255 255 / 15%);
          }
          &.focused,
          &:hover {
            background: rgb(75 115 255 / 50%);
          }
        }
      providers: ['glazewm']
      events:
        - type: 'click'
          fn_path: 'script.js#focusWorkspace'
          selector: '.workspace'
      template: |
        @for (workspace of glazewm.currentWorkspaces) {
          <button
            class="workspace {{ workspace.hasFocus ? 'focused' : '' }} {{ workspace.isDisplayed ? 'displayed' : '' }}"
            id="{{ workspace.name }}"
          >
            {{ workspace.displayName ?? workspace.name }}
          </button>
        }
  group/center:
    styles: |
      justify-self: center;
  group/right:
    styles: |
      justify-self: end;
      display: flex;
      .template {
        margin-left: 4px;
      }
    template/cpu:
      providers: ['cpu']
      styles: |
        margin-right: 8px;
        margin-left: 0px;
        .high-usage {
          color: #ff0000;
        }
      template: |
        <i class="nf nf-oct-cpu"></i>
        @if (cpu.usage > 85) {
          <span class="high-usage">{{ Math.round(cpu.usage) }}%</span>
        } @else {
          <span>{{ Math.round(cpu.usage) }}%</span>
        }
    template/memory:
      providers: ['memory']
      styles: |
        margin-right: 8px;
        margin-left: 0px;
      template: |
        <i class="nf nf-oct-stack"></i>
        {{ Math.round(memory.usage) }}%
    template/battery:
      providers: ['battery']
      styles: |
        margin-right: 8px;
        margin-left: 0px;
        position: relative;
        .charging-icon {
          position: absolute;
          left: 4px;
          right: 4px;
        }
      template: |
        @if (battery.chargePercent > 90) {<i class="nf nf-md-battery_90"></i>}
        @else if (battery.chargePercent > 70) {<i class="nf nf-md-battery_70"></i>}
        @else if (battery.chargePercent > 40) {<i class="nf nf-md-battery_40"></i>}
        @else if (battery.chargePercent > 20) {<i class="nf nf-md-battery_20"></i>}
        @else {<i class="nf nf-md-battery_10"></i>}
        {{ Math.round(battery.chargePercent) }}%
    template/clock:
      providers: ['date']
      styles: |
        margin-right: 8px;
        margin-left: 0px;
      template: |
        <i class="nf nf-fa-calendar"></i>
        {{ date.toFormat(date.now, 'yyyy-MM-dd HH:mm') }}
